#!/bin/bash
res=${1-0.5km}

ncore=${2-$NR_CPUS}

tmax=3000			# to get better read on matvec

export OMP_NUM_THREADS=1


hmat=4;
hmat_flag="-use_hmatrix $hmat -hmmvp_tol 1e-4"


oname=lr.$res.$hmat

wdir=$HOST.$res

mkdir -p $wdir
cd $wdir

lfile=log.$oname.dat
if [ ! -s $lfile ];then    
    echo $0: in `pwd`, writing to $lfile deleting output
    rm -r tmp_rsf/*
    date > $lfile
    mpirun -np $ncore  ../../bin/rsf_solve  \
	   -geom_file   ../"geom_bp5_"$res".in" -rsf_file    ../"rsf_bp5_"$res".dat"   \
	   -rsf_ic_file ../"ic_bp5_"$res".in"   -rsf_dc_file ../"dc_bp5_"$res".in"   \
	   $hmat_flags -shear_modulus 3.204e10 -s_wave_speed 3464 \
	   -f0 0.6 -dc 0.14 -vpl 1e-9 -v0 1e-6 -sigma_init 25e6  \
	   -rtol 1e-4 -ts_rk_type 3bs -stop_time_yr $tmax \
	   -ts_max_steps 2000000  -field_step_interval 250 -rsf_catalog -rsf_rupture_time \
	   -print_interval_yr 0.02  -rupture_vth 0.1 -log_view 2>> $lfile >> $lfile
    date >> $lfile
    cd ..
else
    echo $0: found $lfile in $wdir
fi


