#!/bin/bash
# style of H mat, 1,3,4
hmat=${1-0}
ress=${2-"1km 0.5km 0.25km"}
ncore=${3-24}
# local_norm
#tmax=500
tmax=3000			# to get better read on matvec

export OMP_NUM_THREADS=1
#
# set the tolerance flags, and try to make comparable to each other
#
if [ $hmat = 0 ];then
    tol_flag=""
    epsv=inf
elif [ $hmat = 1 ];then		# htools
    epsv="1e-3 1e-4 1e-5 1e-6"
    tol_flag="-mat_htool_eta 3 -mat_htool_epsilon" # make eta comparable
elif [ $hmat = 3 ];then		# hacapk
    epsv="1e-3 1e-4 1e-5 1e-6"
    tol_flag="-hacapk_inorm 3 -hacapk_ztol" # matrix-relative norm: better coherent (loading) response here than hacapk's absolute mode 1
elif [ $hmat = 4 ];then		# HMMVP
    epsv="1e-2 1e-3 1e-4 1e-5 1e-6"
    tol_flag="-hmmvp_inorm 1  -hmmvp_tol" # block-local BREM: preserves coherent loading / recurrence timing (now the code default too)
else
    echo $0: error
    exit
fi

mkdir -p ntest.$hmat
cd ntest.$hmat
for res in $ress;do
    for eps in $epsv;do
	oname=$res.$hmat.$eps
	lfile=log.$oname.dat
	if [ ! -s $lfile ];then
	    
	    echo $0: writing to $lfile
	    if [ $eps = inf ];then
		flags=""
	    else
		flags="$tol_flag $eps"
	    fi
	    
	    date > $lfile
	    mpirun -np $ncore  ../../bin/rsf_solve  \
		   -geom_file   ../"geom_bp5_"$res".in" -rsf_file    ../"rsf_bp5_"$res".dat"   \
		   -rsf_ic_file ../"ic_bp5_"$res".in"   -rsf_dc_file ../"dc_bp5_"$res".in"   \
		   -use_hmatrix $hmat $flags -shear_modulus 3.204e10 -s_wave_speed 3464 \
		   -f0 0.6 -dc 0.14 -vpl 1e-9 -v0 1e-6 -sigma_init 25e6  \
		   -rtol 1e-4 -ts_rk_type 3bs -stop_time_yr $tmax \
		   -ts_max_steps 2000000   -print_interval_yr 0.02 -log_view 2>> $lfile >> $lfile
	    date >> $lfile
	    for f in rsf_events rsf_monitor rsf_stats;do
		if [ ! -s $f.dat ];then
		    echo $0: $f. dat not produced for $oname
		    exit
		fi
		mv $f.dat $f.$oname.dat
		
	    done
	else
	    echo $0: not rerunning, $lfile exists
	fi
	
    done
done
cd ..
