#!/bin/bash

reg=-R500/5000/-20/2
proj=-JX7/4
fs=""
for p in PD06 PD07 PD13;do

    ofile=$p.ps

    psbasemap -Ba500f100:"time [yr]":/a3f1:"@[\log_{10}(v [\mathrm{m/s}]@["::.$p:WeSn -P -K $reg $proj > $ofile
    gawk '{if(NR>2)print($3,$5)}' $p/rsf_monitor.g000.dat > tmp.dat
    minmax tmp.dat
    psxy tmp.dat $reg $proj -W2,black -O -K >> $ofile
    rm tmp.dat
    i=1
    si=`echo $i | gawk '{printf("g%03i",$1)}'`
    xl=600;dxl=250;yl=1
    while [ -s $p/rsf_monitor.$si.dat ];do
	echo  $p/rsf_monitor.$si.dat
	col=`platecolor $i`
	gawk '{if(NR>2)print($3,$5)}' $p/rsf_monitor.$si.dat | psxy $reg $proj -W2,$col -O -K >> $ofile
	echo $xl $yl 18 0 29 LM "S$i" | pstext $reg $proj -O -K -F+f$col >> $ofile
	((i=i+1))
	((xl=xl+dxl))
	si=`echo $i | gawk '{printf("g%03i",$1)}'`
    done
    psxy -T $reg $proj -O >> $ofile
    modifybb $ofile
    fs="$fs $ofile"
done
epsmerge -par -x 1 -y 3 $fs > cascadia.ps
modifybb cascadia.ps 1
rm $fs
