#
# flags for PETSC support
#
# the 32 bit versions work with Htools
#PETSC_ARCH = arch-linux-c-opt
#PETSC_HTOOL_USED=-DUSE_PETSC_HMAT
#PETSC_ARCH = arch-linux-c-debug
#PETSC_HTOOL_USED=-DUSE_PETSC_HMAT
#
# the 64 bit integer evrsion does not
PETSC_ARCH = arch-linux-c-opt64
PETSC_HTOOL_USED=



PETSc.pc := $(PETSC_DIR)/$(PETSC_ARCH)/lib/pkgconfig/PETSc.pc

# Additional libraries that support pkg-config can be added to the list of PACKAGES below.
PACKAGES := $(PETSc.pc)

CC := $(shell pkg-config --variable=ccompiler $(PACKAGES))
CXX := $(shell pkg-config --variable=cxxcompiler $(PACKAGES))
FC := $(shell pkg-config --variable=fcompiler $(PACKAGES))
SCARGS_OTHER := $(shell pkg-config --cflags-only-other $(PACKAGES))
SCARGS := $(shell pkg-config --variable=cflags_extra $(PACKAGES)) $(CFLAGS_OTHER)
CXXFLAGS := $(shell pkg-config --variable=cxxflags_extra $(PACKAGES)) $(CFLAGS_OTHER)
SFARGS := $(shell pkg-config --variable=fflags_extra $(PACKAGES)) 


CPPFLAGS := $(shell pkg-config --cflags-only-I $(PACKAGES))
PETSC_LDIR := $(shell pkg-config --libs-only-L --libs-only-other $(PACKAGES))
PETSC_LDIR += $(patsubst -L%, $(shell pkg-config --variable=ldflag_rpath $(PACKAGES))%, $(shell pkg-config --libs-only-L $(PACKAGES)))
PETSC_LIBADD := $(shell pkg-config --libs-only-l $(PACKAGES)) -lm


PETSC_INCLUDES = -I$(PETSC_DIR)/include/ $(CPPFLAGS) -DUSE_PETSC $(PETSC_HTOOL_USED)
#
#
PETSC_LIBS = -L$(PETSC_DIR)/lib/  $(PETSC_LDIR) $(PETSC_LIBADD)  # -L/disk/rh_usr_local/intel/oneapi/mpi/latest/lib/

MPICC = mpicc
MPILD = mpif77

