#!/bin/bash
make

# for plotting, and for compute
#tmin=9.9999e7;tmaxc=1e8;tminc=0.9999e8
tmin=.999e6;tmaxc=1e6;tminc=0.9999e6

for k in 0.85765 0.857651;do
    for i in 0 1;do
	f=`echo $k $i | gawk '{printf("state.%020.15f.%i.dat",$1,$2)}'`
	if [ ! -s $f ];then
	    # IC dependence only for small eps
	    (bin/rs2_solver -eps 1e-5 -knd $k  -imode $i -log_state -t_final $tmaxc -monitor_tmin $minc -event_tmin $tminc  -atol 1e-12 -rtol 1e-10 _)&
	else
	    echo $0: reusing $f
	fi
    done
done
wait
echo $0: plotting
cat <<EOF | gnuplot
set term post  enh color solid
set out 'p3w.ps'
set xlabel 'x'
set ylabel 'y'
set zlabel 'z'
splot 'state.0000.857650000000000.0.dat' using ((\$1>=$tmin)?(\$2):(1/0)) : 3 : 4 title 'k = 0.857650 (IC1)' w l,\
      'state.0000.857650000000000.1.dat' using ((\$1>=$tmin)?(\$2):(1/0)) : 3 : 4 title 'k = 0.857650 (IC2)' w p,\
      'state.0000.857651000000000.0.dat' using ((\$1>=$tmin)?(\$2):(1/0)) : 3 : 4 title 'k = 0.857651 (IC1)' w l,\
      'state.0000.857651000000000.1.dat' using ((\$1>=$tmin)?(\$2):(1/0)) : 3 : 4 title 'k = 0.857651 (IC2)' w p
EOF

modifybb p3w.ps 1
