#!/bin/bash
redo=${1-0}
npanel=${2-3}

./plot_basins b74e b77e basins_eig 1e3 $npanel $redo 

./plot_basins b74e_513z b77e_513z basins_eig_zoom 1e4 $npanel $redo 

./plot_basins b74e_1025z b77e_1025z basins_eig_zoomh 1e4 $npanel $redo 

./plot_basins b74e_513zz b77e_513zz basins_eig_zoom2 1e5 $npanel $redo 
