#!/bin/bash
#
# single-patch (spring-slider) benchmark for rsf_solve: compares the
# state evolution laws (physics) and the ODE solvers (cost for given
# accuracy) on a 10 x 10 km Okada patch loaded by backslip, which
# cycles with ~142 yr recurrence at the parameters below.
#
# produces results/<variant>_<solver>_<rtol>/ run directories plus a
# reference run per law variant; analyze_slider.py turns these into a
# physics table and work-precision data.
#
# for no radiation damping, set to zero
rd_fac=${1-1.0}
if [ $rd_fac = 1.0 ];then
    odir=results
else
    odir=results.rdf.$rd_fac
fi
#
bindir=../bin
geom=geom_slider10.in		# 10 km patch, half-lengths in meters
# lab inspired
rsf=rsf_slider.in		# a = 0.01, b = 0.015
echo 0.01 0.015 > $rsf
pars="-f0 0.6 -dc 0.008 -vpl 1e-9 -v0 1e-6 -sigma_init 50e6"
#
tmax=450			# [yr]
maxsteps=20000000

common="-shear_modulus 3.204e10 $pars -s_wave_speed 3464 -rsf_catalog -rupture_vth 0.1"
#
# law variants: label, -state_law, extra flags
variants="aging:1: slip:2: prz:3: sato:4: kt:5:"
# solvers: label, flags (imex stage solvers keep their built-in defaults)
solvers="3bs:-ts_rk_type,3bs 5dp:-ts_rk_type,5dp imex:-imex"
#rtols="1e-4 1e-5 1e-6"
rtols="1e-4 1e-5 1e-6 1e-7 1e-8 1e-9"
# reference: 5dp at tight tolerance, one per law variant
ref_rtol=1e-9

#monitor="-dt_monitor_yr  0.1"
monitor="-rdx_monitor   1e-5"
#
mkdir -p $odir
for v in $variants;do
    lab=`echo $v | cut -d: -f1`;law=`echo $v | cut -d: -f2`
    extra=`echo $v | cut -d: -f3 | tr ',' ' '`
    #
    # reference run
    d=$odir/${lab}_ref
    if [ ! -s $d/DONE ];then
	mkdir -p $d
	(cd $d;timeout 200 mpirun  -np 1 ../../$bindir/rsf_solve -geom_file ../../$geom \
	     -rsf_file ../../$rsf -rd_fac $rd_fac  -state_law $law $extra $common \
	     -ts_rk_type 5dp -rtol $ref_rtol -stop_time_yr $tmax $monitor \
	     -ts_max_steps $maxsteps > log.dat 2>&1; echo $? > DONE)
	echo done reference $lab
    fi
    #
    # solver x tolerance matrix
    for s in $solvers;do
	slab=`echo $s | cut -d: -f1`
	sflag=`echo $s | cut -d: -f2 | tr ',' ' '`
	for rtol in $rtols;do
	    d=$odir/${lab}_${slab}_${rtol}
	    if [ ! -s $d/DONE ];then
		mkdir -p $d
		(cd $d;timeout 200 mpirun  -np 1 ../../$bindir/rsf_solve -geom_file ../../$geom \
		     -rsf_file ../../$rsf -state_law $law $extra $common $monitor \
		     $sflag -rd_fac $rd_fac  -rtol $rtol -stop_time_yr $tmax \
		     -ts_max_steps $maxsteps > log.dat 2>&1; echo $? > DONE)
		echo done $lab $slab $rtol
	    fi
	done
    done
done
echo all runs complete
