#!/bin/bash
#

for force_run in 1 0;do

    ./run_test "1 2 3 4 5 6 7 8" "vert dip" "0 2" $force_run 1

    ./run_test "9 10 11" "vert dip" "0 2" $force_run 1
    mv comb.ps comb_fault_18.ps
    mv comb.ps comb_stress_911.ps
done

