#!/bin/bash
#ntests=${1-"1 2 3 4 5 6 7 8 9 10 11 12"}	# 1...8: different fault loading 9.... 11: field computations 12: line
ntests=${1-"1 4 "}	# 1...8: different fault loading 9.... 11: field computations 12: line
#ntests=${1-"11"}	# 
#ntests=${1-"1"}
#angles=${2-"vert dip"}			# vert or dip
angles=${2-"dip"}			# vert or dip
#angles=${2-"vert"}			# vert or dip
#
# geometry
#
# 0: quad 1: iquad 2: triangle 2b 2c 2d: different integration for triangles 3: equilateral triangle
#geoms=${3-"0 1 2"}			
geoms=${3-"0 1 2 2c 2d 3"}			
#geoms=${3-0}
force_run=${4-1}
#
combine_plots=${5-1}
#bumpy=${6-1}
bumpy=${6-0}

show_edges=1
binary=interact

reg=-R-11/11/-11/11/-4/0
rscale=.3

fs=""
for ntest in $ntests;do
    for angle in $angles;do
	if [ $ntest -le 8 ];then
	    strike0=30;l0=10;w0=3		#

	    #no=60;mo=20
	    #no=90;mo=30
	    no=30;mo=10
	    #no=6;mo=2
	    z=-3
	elif [ $ntest -le 11 ];then
	    strike0=40;
	    #w0=3;l0=10
	    w0=2;l0=3
	    no=10;mo=4
	    #no=1;mo=2
	    z=-3
	else
	    strike0=0;
	    w0=1;l0=1
	    no=2;mo=2
	    z=-1

	fi
	if [ $angle = "vert" ];then	# vertical
	    strike=$strike0;dip=90
	elif [ $angle = "dip" ];then	# dip
	    strike=$strike0;dip=10
	else
	    echo $0: error $angle
	    exit
	fi
	rm last_rms.*.dat 	# those are used to keep same colorscale
	gc=1
	for geom in $geoms;do
	    if [[ $gc = 1 ]];then
		adjust=1	# compute and save RMS for the first geometry
	    else
		adjust=2	# read in RMS 
	    fi
	    if [ $bumpy -eq 0 ];then
		if [ $geom != 3 ];then
		    makefault -strike $strike -dip $dip -n $no -m $mo -l $l0 -z $z -w $w0  > rgeom.in # reference quad geometry
		fi
	    else
		if [ $geom -eq 3 ];then
		    echo $0: equi tri geom $geom not set up for bumpy
		    exit
		fi
		bamp=0.1
	    fi
	    if [ $geom = 0 ];then
		if [ $bumpy = 0 ];then
		    if [ $geom != 3 ];then
			cp rgeom.in geom.in
		    fi
		else
		    # quad approximation
		    ppcodes="1 0 0 0"
		    ac=0
		    awk -v cx=0 -v cy=0 -v cz=$z -v strike=$strike -v dip=$dip -v L=$l0 -v W=$w0 -v nx=$no -v ny=$mo \
			-v as=$bamp -v lam_s=$l0 -v ad=$bamp -v lam_d=$w0 -v tri_mode=$ac -f make_curved_points.awk  | \
			points2patch $ppcodes > geom.in
		fi

		glabel=quad
	    elif [ $geom = 1 ];then
		if [ $bumpy = 0 ];then
		    # convert quads to iquads 
		    cat rgeom.in  | patch2vertices | points2patch 0 0 0 1 > geom.in
		else
		    ppcodes="0 0 0 1"
		    ac=0
		    awk -v cx=0 -v cy=0 -v cz=$z -v strike=$strike -v dip=$dip -v L=$l0 -v W=$w0 -v nx=$no -v ny=$mo \
			-v as=$bamp -v lam_s=$l0 -v ad=$bamp -v lam_d=$w0 -v tri_mode=$ac -f make_curved_points.awk  | \
			points2patch $ppcodes > geom.in
		fi
		glabel=iquad
	    elif [[ $geom = 2 || $geom = 2a || $geom = 2b || $geom = 2c || $geom = 2d ]];then
		((nu=no));((mu=mo/2))
		if [ $geom = 2 ];then
		    glabel="tri-CTR"
		elif [ $geom = 2c ];then
		    glabel="tri-3(HYB)"
		elif [ $geom = 2d ];then
		    glabel="tri-4(mixed)"
		else
		    glabel="tri"$geom
		fi
		if [ $bumpy = 0 ];then
		    #cat rgeom.in | patchquad2patchtri 2 > geom.in
		    #cat rgeom.in | patchquad2patchtri 1 > geom.in
		    cat rgeom.in | patchquad2patchtri 0 > geom.in
		else
		    # triangles
		    ppcodes="0 0 0 2"
		    ac=1 # or 2 or 3
		    awk -v cx=0 -v cy=0 -v cz=$z -v strike=$strike -v dip=$dip -v L=$l0 -v W=$w0 -v nx=$no -v ny=$mo \
			-v as=$bamp -v lam_s=$l0 -v ad=$bamp -v lam_d=$w0 -v tri_mode=$ac -f make_curved_points.awk  | \
			points2patch $ppcodes > geom.in
		fi
		#cat geom.in
		#exit
	    elif [[ $geom = 3 ]];then # equilaterial
		dx=`echo $l0 $no | gawk '{print($1/$2*2)}'`
		makefault -strike $strike -dip $dip -l $l0 -z $z -w $w0  |  \
		    patch2vertices | ../src/util/quad2trimesh.sh -$dx -1 | tri2patch 20 > geom.in
		glabel="etri"
	    else
		echo $0: geom error
		exit
	    fi
	    rm smlin.in rgeom.in 2> /dev/null
	    if [[ $ntest -eq 1 ]];then # prescribed slip
		bc_type=0;bc_val=1;bc_name="prescribed u@-strike@-"
	    elif [[ $ntest -eq 2 ]];then
		bc_type=1;bc_val=1;bc_name="prescribed u@-dip@-"
	    elif [[ $ntest -eq 3 ]];then
		bc_type=2;bc_val=1;bc_name="prescribed u@-normal@-"
	    elif [[ $ntest -eq 4 ]];then # prescribed stress
		bc_type=10;bc_val=-2e3;bc_name="prescribed @~t@~@-strike@-"
	    elif [[ $ntest -eq 5 ]];then
		bc_type=20;bc_val=-2e3;bc_name="prescribed @~t@~@-dip@-"
	    elif [[ $ntest -eq 6 ]];then
		bc_type=30;bc_val=-2e3;bc_name="prescribed @~t@~@-normal@-"
	    elif [[ $ntest -eq 7 || $ntest = 8 ]];then
		if [ $ntest = 7 ];then
		    bc_type=50;bc_name="@~t@~@-strike@- = @~t@~@-dip@- = 0"
		else
		    bc_type=51;bc_name="@~s@~@-c@- = 0"
		fi
		bc_val=-1
		    
		cat <<EOF > smlin.in
-1e3 0
1.6e3 0
0 0
-1e3 0
0 0  
0 0
EOF
		
	    elif [[ $ntest -eq 9 ]];then
		bc_type=0;bc_val=1;bc_name="prescribed u@-strike@-"
	    elif [[ $ntest -eq 10 ]];then
		bc_type=1;bc_val=1;bc_name="prescribed u@-dip@-"
	    elif [[ $ntest -eq 11 ]];then
		bc_type=2;bc_val=1;bc_name="prescribed u@-normal@-"
	    elif [[ $ntest -eq 12 ]];then
		bc_type=0;bc_val=1
	    else
		echo $0: test $ntest error
		exit
	    fi
	    if [ $ntest -le 8 ];then # only check fault slip
		pf=0
	    elif  [ $ntest -le 11 ];then # field
		pf=1;ft=1
	    else
		pf=1;ft=0
	    fi
	    echo 1 $pf > bc.in
	    if [ $pf -eq 1 ];then
		if [ $ft = 1 ];then
		    cat <<EOF >> bc.in
-30 30 241 -30 30 241 -6 0 3
EOF
		else
		    cat <<EOF >> bc.in
-30 30 241 0 0 1 -1 -1 1
EOF
		fi

	    fi
	    echo
	    echo test number $ntest
	    echo bc_type $bc_type bc_val $bc_val
	    echo 
	    cat <<EOF	>> bc.in		
-1 -1 -1 $bc_type $bc_val
EOF


	    oname=$angle.$geom.$ntest
	    if [[ $force_run -eq 0 && -s  geoms/geom.$oname.in && -s flt_dat/flt.$oname.dat ]];then
		echo
		echo $0: reusing output geom $geom $oname  `lc geoms/geom.$oname.in` elements
		echo
	    else
		#flags="-sv "
		flags=""
		if [ $geom = 2a ];then
		    flags="$flags -tv 1"
		elif [ $geom = 2b ];then
		    flags="$flags -tv 2"
		elif [ $geom = 2c ];then
		    flags="$flags -tv 3"
		elif [ $geom = 2d ];then
		    flags="$flags -tv 4"
		fi
		rm flt.dat stress.out disp.out 2> /dev/null
		#mpirun -np 16 $binary $flags -ksp_type fgmres -pc_type none -ksp_max_it 50000 -ksp_rtol 1.0e-7
		#mpirun -np 16 $binary $flags 	-pc_factor_mat_solver_type scalapack -mat_type scalapack
		$binary $flags

		mv geom.in geoms/geom.$oname.in
		mv flt.dat flt_dat/flt.$oname.dat
		mv bc.in bcs/bc.$oname.in
		if [ $pf = 1 ];then
		    mv disp.out disp_dat/disp.$oname.out
		    mv stress.out stress_dat/stress.$oname.out
		    mv stress.hdr stress_dat/stress.$oname.hdr
		fi
	    fi
	    if [[ $bc_type = 50 || $bc_type = 51 ]];then
		label="$bc_name, $glabel"
	    else
		label="$bc_name = $bc_val, $glabel elements"
	    fi
	    #echo $0: plotting
	    if [ $combine_plots -eq 1 ];then
		if [ $pf = 0 ];then
		    echo 
		    echo $0: plotting with geom $geom adjust $adjust ntest $ntest
		    echo 
		    ../plotting/plot_fault_solution flt_dat/flt.$oname geoms/geom.$oname.in \
						    "$label" $reg $rscale $adjust $show_edges 
		    fs="$fs  flt_dat/flt.$oname.ps"
		else
		    if [ $ft = 1 ];then
			cp disp_dat/disp.$oname.out .
			cp stress_dat/stress.$oname.out .
			cp stress_dat/stress.$oname.hdr .
			../plotting/plot_displacement_and_stress $oname 0 "$label"
			rm stress.$oname.out   stress.$oname.hdr disp.$oname.out 
		    else
			echo 
		    fi
		    fs="$fs stress.$oname.ps"
		fi
	    else
		if [ $pf = 0 ];then
		    echo 
		    echo $0: plotting with geom $geom adjust $adjust ntest $ntest
		    echo 
		    ../plotting/plot_fault_solution flt_dat/flt.$oname geoms/geom.$oname.in "$label" $reg $rscale $adjust $show_edges 
		    #gv flt.$oname.ps &
		#else
		    #../plotting/plot_displacement_and_stress $oname "0 -3 -6" "$label"
		    #gv stress.$oname.ps &
		fi
	    fi
	    ((gc=gc+1))
	done 			# end geometry lopp
	if [[ $pf = 1 && $ft = 1 ]];then
	    ./compare_solutions $ntest $angle 1
	    ./compare_solutions $ntest $angle 2
	fi

    done
done
wait
if [ $combine_plots -eq 1 ];then
    if [ $pf = 1 ];then
	epsmerge -par -x 1 -y 1 --orientation Portrait $fs > comb.ps
    else
	epsmerge -par -x 1 -y 1 --orientation Landscape $fs > comb.ps
    fi
    ps2pdf comb.ps
    rm comb.ps
fi
