#!/bin/bash
#
# create BP5 kind of run
#
m=${1-bp5}			# name decides imex and creep law
res=${2-0.5km}
hmode=${3-3}			# H matrix modes 1: pretty bad/slow 2: ok 3: best?
ncore=${4-$NR_CPUS}
restart=${5-0}

mkdir -p $m
cd $m

tmax=3000			# to get better read on matvec
#
# use diretory to decide options
#
cwd=`pwd`
wdir=`basename $cwd`


#rtol=1e-4
rtol=1e-5

case $wdir in 			# decide on type of computation
    bp5)
	imex=0
	evol_law=1
	;;
    bp5_imex)
	imex=1
	evol_law=1
	;;
    bp5_prz)
	imex=0
	evol_law=3
	;;
    bp5_prz_imex)
	imex=1
	evol_law=3
	;;
    bp5_sato)
	imex=0
	evol_law=4
	;;
    bp5_sato_imex)
	imex=1
	evol_law=4
	;;	
    bp5_sl)
	imex=0
	evol_law=2
	;;
    bp5_sl_imex)
	imex=1
	evol_law=2
	;;
    bp5_prz_hfine)
	imex=0
	rtol=1e-6
	evol_law=3
	;;
    *)
	echo $0: cannot determine settings from $wdir
	exit
b	;;
esac

if [ $imex = 1 ];then
    imex_flag="-imex"
else
    imex_flag=""
fi
#

export OMP_NUM_THREADS=1
TACC=${TACC:-0}
if [ $TACC -eq 1 ];then		# host name
    host=TACC
    mbin="ibrun"
else
    mbin="mpirun -bind-to core -map-by socket  -np $ncore"
    host=${HOST:-unknown_host}
fi
#
# working dir for this host
#
sub_dir=$host.r.$res
# 
# h matrix modes, and possibly modify subdirectory name
#

hmat_tol=1e-4
rk_type="-ts_rk_type 3bs "
if [ $hmode -eq 1 ];then	# default
    hmat_flags="-use_hmatrix 4  -hmmvp_inorm 3 -hmmvp_tol $hmat_tol"
elif [ $hmode -eq 2 ];then
    hmat_tol=1e-5
    hmat_flags="-use_hmatrix 4  -hmmvp_inorm 3 -hmmvp_tol $hmat_tol"
elif [ $hmode -eq 3 ];then
    hmat_flags="-use_hmatrix 3  -hacapk_ztol  $hmat_tol"
elif [ $hmode -eq 4 ];then
    hmat_flags="-use_hmatrix 4  -hmmvp_inorm 3 -hmmvp_tol $hmat_tol"
    rk_type="-ts_rk_type 5dp"
elif [ $hmode -eq 5 ];then
    	rtol=1e-6
	hmat_flags="-use_hmatrix 3  -hacapk_ztol  $hmat_tol"
fi
if [ $hmode -ne 1 ];then
    sub_dir=$sub_dir.$hmode
fi

mkdir -p $sub_dir
cd $sub_dir
if [ $restart -eq 1 ];then
    rs_flags="-rsf_restart rsf_checkpoint.bin"
else
    rs_flags=""
fi
oname=lr.r.$res.e.$evol_law.h,$hmode
lfile=log.$oname.dat
if [[ $restart -eq 1 ||  ! -s $lfile ]];then    
    echo $0: in `pwd`, writing to $lfile deleting output
    rm -r tmp_rsf/* 2> /dev/null
    date > $lfile
    $mbin  ../../../bin/rsf_solve  \
	   -geom_file   ../../bp5/"geom_bp5_"$res".in" -rsf_file    ../../bp5/"rsf_bp5_"$res".dat"   \
	   -rsf_ic_file ../../bp5/"ic_bp5_"$res".in"   -rsf_dc_file ../../bp5/"dc_bp5_"$res".in"   \
	   $hmat_flags -shear_modulus 3.204e10 -s_wave_speed 3464 $imex_flag -state_law $evol_law \
	   -f0 0.6 -dc 0.14 -vpl 1e-9 -v0 1e-6 -sigma_init 25e6  -rsf_checkpoint 200000 \
	   -rtol $rtol $rk_type -stop_time_yr $tmax -slip_line_dt_yr 5 \
	   -ts_max_steps 200000000  -rsf_catalog -rsf_rupture_time -domain_check_max_reject -1 \
	   -print_interval_yr 0.02  -rupture_vth 0.01 -log_view 2>> $lfile >> $lfile
    date >> $lfile
    cd ..
else
    echo $0: found $lfile in $sub_dir
fi


cd ..
