/*

  this code is mainly generated by Claude 


  basin_rs2: basins of attraction and Lyapunov spectra for the
  two-state-variable rate-state friction slider of Gu et al. (1984) /
  Becker (2000), non-dimensionalized as in ode_solve_test.c:

     x = log(V/V0), y = (tau-tau0)/A, z = beta2 log(V0 theta2 / L2)

     ydot = k (1 - e^x)
     zdot = -e^x r (b2 x + z)
     xdot = e^x ((b1-1) x + y - z) + ydot - zdot

  For each initial condition on a 2-D grid of perturbations around the
  steady state {0,0,0}, the code

  (1) integrates a transient phase (state only, 3-D),

  (2) integrates state plus the full tangent (variational) system
      (12-D) using the analytical Jacobian

        J = [ f0 - f1 + E(b1-1-k+r b2)   E     E(r-1) ]
            [ -kE                        0     0      ]
            [ f2 - r b2 E                0    -rE     ]

      with E=e^x, f0=xdot, f1=ydot, f2=zdot (verified against sympy),
      accumulating the Lyapunov spectrum via Gram-Schmidt
      renormalization (Benettin et al., 1980),

  (3) records Poincare section crossings x=0 (one direction) via the
      TS event handler and clusters the (y,z) section values to count
      the orbit period,

  (4) classifies the attractor: chaotic if lambda_1 > lam_tol,
      otherwise periodic with the clustered period count.

  Output (per-rank files, one line per grid point; concatenate the
  rank files and use the coordinate columns, not line order):

     e1 e2 lambda1 lambda2 lambda3 nperiod class nevents

     class: 0 = periodic, 1 = chaotic, 2 = unclassified (no events or
     ambiguous)

  MPI-parallel over grid points (each rank runs serial TS instances).

  Main options (defaults in parentheses):

    -knd <val>      normalized stiffness kappa' (0.8574)
    -c1,-c2 <0..2>  perturbed components spanning the IC plane (0,1)
    -c3val <val>    value of the remaining component (0)
    -e1min,-e1max,-n1, -e2min,-e2max,-n2   grid (-2e-3..2e-3, 32)
    -t_trans <val>  transient time, state only (2e4)
    -t_run <val>    Lyapunov/event accumulation time (2e4)
    -no_lyap        skip tangent integration (period counting only)
    -lam_tol <val>  lambda_1 threshold for chaos (1e-3)
    -cluster_tol    (y,z) clustering tolerance for period count (1e-4)
    -atol,-rtol     integrator tolerances (1e-12, 1e-10)
    -oprefix <str>  output file prefix; each MPI rank writes
                    <prefix>.<rank>.dat, flushed per point (basin)
    -dt_renorm      max time between renormalizations (10)
    -verbose        per-point log to stderr

  compile: see makefile (needs PETSc, tested with 3.19)

*/
#include "ode_headers.h"







/* reject steps whose accepted state is out of domain (cf. ode_solve_test.c) */
static PetscErrorCode myDomainError(TS ts,PetscReal time,Vec X,PetscBool *accept)
{
  const PetscScalar *x;
  PetscInt i,n;
  PetscFunctionBeginUser;
  PetscCall(VecGetArrayRead(X,&x));
  PetscCall(VecGetSize(X,&n));
  *accept = PETSC_TRUE;
  if(PetscRealPart(x[0]) > 700.0)
    *accept = PETSC_FALSE;
  for(i=0;i < n;i++)
    if(!isfinite(PetscRealPart(x[i])))
      *accept = PETSC_FALSE;
  PetscCall(VecRestoreArrayRead(X,&x));
  PetscFunctionReturn(PETSC_SUCCESS);
}

/* cubic Hermite value on [0,1] given endpoint values/derivatives (dt-scaled) */
static PetscReal hermite(PetscReal s,PetscReal p0,PetscReal m0,PetscReal p1,PetscReal m1)
{
  PetscReal s2 = s*s,s3 = s2*s;
  return (2.*s3 - 3.*s2 + 1.)*p0 + (s3 - 2.*s2 + s)*m0 +
    (-2.*s3 + 3.*s2)*p1 + (s3 - s2)*m1;
}
/* detect downward x[0]=0 crossing between the previous and current accepted
   step; if found, record Hermite-interpolated (y,z) at the crossing */
static PetscErrorCode check_crossing(struct AppCtx *par,PetscReal t,const PetscReal x[3])
{
  PetscReal f[3],dt,s0,s1,sm,v0,vm;
  PetscInt i,iter,dir = 0;
  PetscFunctionBeginUser;
  eval_rhs(par,x,f);
  if(par->have_prev){
    if((par->prev_x[0] > 0.0) && (x[0] <= 0.0))
      dir = -1;
    else if((par->prev_x[0] <= 0.0) && (x[0] > 0.0))
      dir = 1;
  }
  if(dir != 0){
    dt = t - par->prev_t;
    if((dt > 0.0) && (par->nevent < par->mevent)){
      /* bisection on the Hermite interpolant of x[0](s), s in [0,1] */
      s0 = 0.0; v0 = par->prev_x[0];
      s1 = 1.0;
      for(iter=0;iter < 60;iter++){
	sm = 0.5*(s0+s1);
	vm = hermite(sm,par->prev_x[0],dt*par->prev_f[0],x[0],dt*f[0]);
	if(((v0 > 0.0) && (vm > 0.0)) || ((v0 <= 0.0) && (vm <= 0.0))){
	  s0 = sm; v0 = vm;
	}else{
	  s1 = sm;
	}
	if(s1 - s0 < 1e-14)
	  break;
      }
      sm = 0.5*(s0+s1);
      par->ey[par->nevent] = hermite(sm,par->prev_x[1],dt*par->prev_f[1],x[1],dt*f[1]);
      par->ez[par->nevent] = hermite(sm,par->prev_x[2],dt*par->prev_f[2],x[2],dt*f[2]);
      par->edir[par->nevent] = dir;
      par->nevent++;
    }
  }
  par->prev_t = t;
  for(i=0;i < 3;i++){
    par->prev_x[i] = x[i];
    par->prev_f[i] = f[i];
  }
  par->have_prev = PETSC_TRUE;
  PetscFunctionReturn(PETSC_SUCCESS);
}

/* modified Gram-Schmidt on the three tangent vectors stored in x[3..11];
   accumulates log norms into par->logsum */
static PetscErrorCode renormalize_tangent(Vec X,struct AppCtx *par)
{
  PetscScalar *x;
  PetscReal nrm,dot;
  PetscInt iv,jv,i,offi,offj;
  PetscFunctionBeginUser;
  PetscCall(VecGetArray(X,&x));
  for(iv=0;iv < 3;iv++){
    offi = BASIN_NSTATE + iv*3;
    for(jv=0;jv < iv;jv++){	/* remove projections on earlier vectors */
      offj = BASIN_NSTATE + jv*3;
      dot = 0.0;
      for(i=0;i < 3;i++)
	dot += PetscRealPart(x[offi+i]) * PetscRealPart(x[offj+i]);
      for(i=0;i < 3;i++)
	x[offi+i] -= dot * x[offj+i];
    }
    nrm = 0.0;
    for(i=0;i < 3;i++)
      nrm += PetscRealPart(x[offi+i]) * PetscRealPart(x[offi+i]);
    nrm = PetscSqrtReal(nrm);
    if(nrm > 0.0){
      par->logsum[iv] += PetscLogReal(nrm);
      for(i=0;i < 3;i++)
	x[offi+i] /= nrm;
    }
  }
  PetscCall(VecRestoreArray(X,&x));
  PetscFunctionReturn(PETSC_SUCCESS);
}

/* after each accepted step: renormalize if enough time elapsed or the
   leading tangent vector has grown large */
static PetscErrorCode myPostStep(TS ts)
{
  struct AppCtx *par;
  Vec X;
  PetscReal t,nrm1,xs[3];
  const PetscScalar *x;
  PetscInt i;
  PetscFunctionBeginUser;
  PetscCall(TSGetApplicationContext(ts,&par));
  PetscCall(TSGetTime(ts,&t));
  PetscCall(TSGetSolution(ts,&X));
  PetscCall(VecGetArrayRead(X,&x));
  for(i=0;i < 3;i++)
    xs[i] = PetscRealPart(x[i]);
  nrm1 = 0.0;
  if(par->do_lyap)
    for(i=0;i < 3;i++)
      nrm1 += PetscRealPart(x[BASIN_NSTATE+i]) * PetscRealPart(x[BASIN_NSTATE+i]);
  PetscCall(VecRestoreArrayRead(X,&x));
  PetscCall(check_crossing(par,t,xs));
  if(par->do_lyap &&
     ((t - par->last_renorm_t > par->dt_renorm) || (nrm1 > par->renorm_max * par->renorm_max))){
    PetscCall(renormalize_tangent(X,par));
    par->last_renorm_t = t;
  }
  PetscFunctionReturn(PETSC_SUCCESS);
}

/* greedy clustering of the (y,z) section values, separately per crossing
   direction so that the total matches the extrema/period count convention
   of the bifurcation diagrams (2 branches per loop); capped */
static PetscInt count_clusters(PetscInt n,const PetscReal *y,const PetscReal *z,
			       const PetscInt *dir,PetscReal tol)
{
  static PetscReal cy[BASIN_MAX_CLUSTER],cz[BASIN_MAX_CLUSTER];
  static PetscInt cd[BASIN_MAX_CLUSTER];
  PetscInt nc = 0,i,j;
  PetscBool found;
  for(i=0;i < n;i++){
    found = PETSC_FALSE;
    for(j=0;j < nc;j++){
      if((dir[i] == cd[j]) && (PetscAbsReal(y[i]-cy[j]) < tol) && (PetscAbsReal(z[i]-cz[j]) < tol)){
	found = PETSC_TRUE;
	break;
      }
    }
    if(!found){
      if(nc >= BASIN_MAX_CLUSTER)
	return nc;
      cy[nc] = y[i]; cz[nc] = z[i]; cd[nc] = dir[i];
      nc++;
    }
  }
  return nc;
}

/*
   integrate one initial condition through transient (3-D) and
   accumulation (12-D or 3-D) phases; returns Lyapunov spectrum, period
   count and classification
*/
static PetscErrorCode run_one(struct AppCtx *par,const PetscReal xinit[3],
			      PetscReal t_trans,PetscReal t_run,
			      PetscReal atol,PetscReal rtol,
			      PetscReal cluster_tol,PetscReal lam_tol,
			      PetscBool verbose,
			      PetscReal lam[3],PetscInt *nperiod,PetscInt *class,PetscInt *nevents)
{
  TS ts;
  Vec X;
  PetscScalar *x;
  PetscInt i,n;
  PetscReal t_end,teff;
  PetscFunctionBeginUser;
  lam[0] = lam[1] = lam[2] = 0.0;
  *nperiod = 0; *class = 2; *nevents = 0;
  par->logsum[0] = par->logsum[1] = par->logsum[2] = 0.0;
  par->nevent = 0;
  par->have_prev = PETSC_FALSE;
  par->overflowed = PETSC_FALSE;

  /* ---- phase A: transient, state only ---- */
  PetscCall(VecCreateSeq(PETSC_COMM_SELF,BASIN_NSTATE,&X));
  PetscCall(VecGetArray(X,&x));
  for(i=0;i < 3;i++)
    x[i] = xinit[i];
  PetscCall(VecRestoreArray(X,&x));
  PetscCall(TSCreate(PETSC_COMM_SELF,&ts));
  PetscCall(TSSetProblemType(ts,TS_NONLINEAR));
  PetscCall(TSSetSolution(ts,X));
  PetscCall(TSSetRHSFunction(ts,NULL,RHSFunction3D,par));
  PetscCall(TSSetFunctionDomainError(ts,myDomainError));
  PetscCall(TSSetType(ts,TSRK));
  PetscCall(TSRKSetType(ts,TSRK8VR));
  PetscCall(TSSetMaxStepRejections(ts,1000000000));
  PetscCall(TSSetTolerances(ts,atol,NULL,rtol,NULL));
  PetscCall(TSSetTime(ts,0.0));
  PetscCall(TSSetTimeStep(ts,1e-5));
  PetscCall(TSSetExactFinalTime(ts,TS_EXACTFINALTIME_STEPOVER));
  PetscCall(TSSetMaxTime(ts,t_trans));
  PetscCall(TSSetFromOptions(ts));
  PetscCall(TSSolve(ts,X));
  PetscCall(TSDestroy(&ts));

  /* ---- phase B: accumulation ---- */
  n = par->do_lyap ? BASIN_NFULL : BASIN_NSTATE;
  {
    Vec Xf;
    const PetscScalar *xa;
    PetscCall(VecCreateSeq(PETSC_COMM_SELF,n,&Xf));
    PetscCall(VecGetArrayRead(X,&xa));
    PetscCall(VecGetArray(Xf,&x));
    for(i=0;i < BASIN_NSTATE;i++)
      x[i] = xa[i];
    if(par->do_lyap){		/* identity tangent */
      for(i=BASIN_NSTATE;i < BASIN_NFULL;i++)
	x[i] = 0.0;
      x[3] = x[7] = x[11] = 1.0;
    }
    PetscCall(VecRestoreArray(Xf,&x));
    PetscCall(VecRestoreArrayRead(X,&xa));
    PetscCall(VecDestroy(&X));
    X = Xf;
  }
  par->last_renorm_t = 0.0;
  PetscCall(TSCreate(PETSC_COMM_SELF,&ts));
  PetscCall(TSSetProblemType(ts,TS_NONLINEAR));
  PetscCall(TSSetApplicationContext(ts,par));
  PetscCall(TSSetSolution(ts,X));
  PetscCall(TSSetRHSFunction(ts,NULL,par->do_lyap ? RHSFunction3DTangent : RHSFunction3D,par));
  PetscCall(TSSetFunctionDomainError(ts,myDomainError));
  PetscCall(TSSetType(ts,TSRK));
  PetscCall(TSRKSetType(ts,TSRK8VR));
  PetscCall(TSSetMaxStepRejections(ts,1000000000));
  PetscCall(TSSetTolerances(ts,atol,NULL,rtol,NULL));
  PetscCall(TSSetTime(ts,0.0));
  PetscCall(TSSetTimeStep(ts,1e-5));
  PetscCall(TSSetExactFinalTime(ts,TS_EXACTFINALTIME_STEPOVER));
  PetscCall(TSSetMaxTime(ts,t_run));
  PetscCall(TSSetPostStep(ts,myPostStep));
  PetscCall(TSSetFromOptions(ts));
  PetscCall(TSSolve(ts,X));
  PetscCall(TSGetTime(ts,&t_end));
  if(par->do_lyap){
    PetscCall(renormalize_tangent(X,par)); /* pick up growth since last renorm */
    teff = (t_end > 0.0) ? t_end : 1.0;
    for(i=0;i < 3;i++)
      lam[i] = par->logsum[i] / teff;
  }
  PetscCall(TSDestroy(&ts));
  PetscCall(VecDestroy(&X));

  /* ---- classify ---- */
  *nevents = par->nevent;
  if(par->nevent > 0)
    *nperiod = count_clusters(par->nevent,par->ey,par->ez,par->edir,cluster_tol);
  if(par->do_lyap){
    /* chaos classification requires section crossings; a trajectory
       stuck on the unstable fixed point (no events) yields positive
       exponents (real parts of the fixed point eigenvalues) but is
       not on a chaotic attractor */
    if(par->nevent > 0)
      *class = (lam[0] > lam_tol) ? 1 : 0;
  }else{
    if(par->nevent > 0)
      *class = (*nperiod >= BASIN_MAX_CLUSTER) ? 1 : 0;
  }
  if(verbose)
    fprintf(stderr,"run_one: knd %g IC (%10.3e,%10.3e,%10.3e) lam (%10.3e,%10.3e,%10.3e) nev %d np %d class %d\n",
	    (double)par->knd,(double)xinit[0],(double)xinit[1],(double)xinit[2],
	    (double)lam[0],(double)lam[1],(double)lam[2],(int)*nevents,(int)*nperiod,(int)*class);
  PetscFunctionReturn(PETSC_SUCCESS);
}

int main(int argc,char **argv)
{
  struct AppCtx par[1];
  PetscReal t_trans,t_run,atol,rtol,cluster_tol,lam_tol;
  PetscReal e1min,e1max,e2min,e2max,c3val;
  PetscInt n1,n2,c1,c2,c3,i1,i2,ipt,npt;
  PetscBool no_lyap,verbose;
  PetscMPIInt rank,size;
  char oprefix[PETSC_MAX_PATH_LEN-32],fname[PETSC_MAX_PATH_LEN];
  FILE *fout;
  PetscReal xinit[3],lam[3],e1,e2;
  PetscInt nperiod,class,nevents;
  PetscFunctionBeginUser;
  PetscCall(PetscInitialize(&argc,&argv,NULL,NULL));
  PetscCallMPI(MPI_Comm_rank(PETSC_COMM_WORLD,&rank));
  PetscCallMPI(MPI_Comm_size(PETSC_COMM_WORLD,&size));

  /* model parameters as in ode_solve_test.c */
  init_stiff_par(par, 0.8574);


  /* run control */
  t_trans = 2e4; t_run = 2e4;
  atol = 1e-12; rtol = 1e-10;
  cluster_tol = 1e-4; lam_tol = 1e-3;
  no_lyap = PETSC_FALSE; verbose = PETSC_FALSE;
  par->dt_renorm = 10.0; par->renorm_max = 1e4;
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-t_trans",&t_trans,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-t_run",&t_run,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-atol",&atol,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-rtol",&rtol,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-cluster_tol",&cluster_tol,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-lam_tol",&lam_tol,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-dt_renorm",&par->dt_renorm,NULL));
  PetscCall(PetscOptionsGetBool(NULL,NULL,"-no_lyap",&no_lyap,NULL));
  PetscCall(PetscOptionsGetBool(NULL,NULL,"-verbose",&verbose,NULL));
  PetscCall(PetscStrncpy(oprefix,"basin",sizeof(oprefix)));
  PetscCall(PetscOptionsGetString(NULL,NULL,"-oprefix",oprefix,sizeof(oprefix),NULL));
  par->do_lyap = no_lyap ? PETSC_FALSE : PETSC_TRUE;

  /* grid of initial condition perturbations */
  c1 = 0; c2 = 1; c3val = 0.0;
  e1min = -2e-3; e1max = 2e-3; n1 = 32;
  e2min = -2e-3; e2max = 2e-3; n2 = 32;
  PetscCall(PetscOptionsGetInt(NULL,NULL,"-c1",&c1,NULL));
  PetscCall(PetscOptionsGetInt(NULL,NULL,"-c2",&c2,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-c3val",&c3val,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-e1min",&e1min,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-e1max",&e1max,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-e2min",&e2min,NULL));
  PetscCall(PetscOptionsGetReal(NULL,NULL,"-e2max",&e2max,NULL));
  PetscCall(PetscOptionsGetInt(NULL,NULL,"-n1",&n1,NULL));
  PetscCall(PetscOptionsGetInt(NULL,NULL,"-n2",&n2,NULL));
  PetscCheck((c1 >= 0) && (c1 <= 2) && (c2 >= 0) && (c2 <= 2) && (c1 != c2),
	     PETSC_COMM_WORLD,PETSC_ERR_ARG_OUTOFRANGE,"-c1/-c2 must be distinct and in 0..2");
  c3 = 3 - c1 - c2;		/* remaining component */

  /* event storage */
  par->mevent = 100000;
  PetscCall(PetscMalloc3(par->mevent,&par->ey,par->mevent,&par->ez,par->mevent,&par->edir));

  if(rank == 0){
    fprintf(stderr,"%s: knd %g k %g grid %d x %d on components %d/%d (comp %d = %g)\n",
	    argv[0],(double)par->knd,(double)par->k,(int)n1,(int)n2,(int)c1,(int)c2,(int)c3,(double)c3val);
    fprintf(stderr,"%s: t_trans %g t_run %g lyap %d lam_tol %g cluster_tol %g ranks %d\n",
	    argv[0],(double)t_trans,(double)t_run,(int)par->do_lyap,(double)lam_tol,(double)cluster_tol,(int)size);
  }
  snprintf(fname,PETSC_MAX_PATH_LEN,"%s.%d.dat",oprefix,(int)rank);
  fout = fopen(fname,"w");
  PetscCheck(fout,PETSC_COMM_SELF,PETSC_ERR_FILE_OPEN,"could not open %s",fname);
  if(rank == 0){
    fprintf(fout,"# knd %.15f c1 %d c2 %d c3 %d c3val %g t_trans %g t_run %g lyap %d\n",
	    (double)par->knd,(int)c1,(int)c2,(int)c3,(double)c3val,(double)t_trans,(double)t_run,(int)par->do_lyap);
    fprintf(fout,"# e1 e2 lambda1 lambda2 lambda3 nperiod class nevents\n");
  }
  npt = n1 * n2;
  for(ipt=rank;ipt < npt;ipt += size){ /* rank-strided over grid */
    i1 = ipt % n1;
    i2 = ipt / n1;
    e1 = (n1 > 1) ? (e1min + (e1max - e1min) * i1 / (PetscReal)(n1 - 1)) : e1min;
    e2 = (n2 > 1) ? (e2min + (e2max - e2min) * i2 / (PetscReal)(n2 - 1)) : e2min;
    xinit[c1] = e1; xinit[c2] = e2; xinit[c3] = c3val;
    PetscCall(run_one(par,xinit,t_trans,t_run,atol,rtol,cluster_tol,lam_tol,verbose,
		      lam,&nperiod,&class,&nevents));
    fprintf(fout,"%17.10e %17.10e %13.6e %13.6e %13.6e %5d %2d %6d\n",
	    (double)e1,(double)e2,
	    (double)lam[0],(double)lam[1],(double)lam[2],
	    (int)nperiod,(int)class,(int)nevents);
    fflush(fout);
  }
  fclose(fout);
  PetscCall(PetscFree3(par->ey,par->ez,par->edir));
  PetscCall(PetscFinalize());
  return 0;
}
