#!/bin/bash
#pimodes=`seq 10 -1 0`
#pimodes="1"
pimodes="0 1"

tmpn=`mktemp`
trap "rm -f $tmpn*" EXIT
#   2     4        8         16         32       64       128          256        512
ks="1 0.866259 0.857038 0.85539350 0.85504990 0.85497670 0.85496100 0.85495770 0.85495690"
# Feigenbaum number
echo $ks | awk '{n=NF;for(i=1;i<=n;i++)k[i]=$i;}END{
for(i=2;i<n;i++)
print(i,(k[i]-k[i-1])/(k[i+1]-k[i]));
}'
# mid values

echo $ks | awk '{n=NF;for(i=1;i<=n;i++)k[i]=$i;}END{
     p=1;
     for(i=2;i<=n;i++)
          printf("//par->knd = %10.8f; // %i orbit\n",
	  (k[i-1]+k[i])/2,p*=2);
}'
#
lfile=px0log.old.dat
#lfile=px0log.dat

if [ ! -s $lfile ];then
    echo $0: unpacking
    for imode in $pimodes;do
	echo $imode
	(zcat $lfile.gz | gawk -v i=$imode '{if($3==i)print($1,$2)}' > $tmpn.$imode)&
    done
    wait
else
    for imode in $pimodes;do
	echo $imode
	(cat $lfile | gawk -v i=$imode '{if($3==i)print($1,$2)}' > $tmpn.$imode)&
    done
    wait
fi

echo $0: unpacking done
for imode in $pimodes;do
    echo $imode nentries `lc $tmpn.$imode`
done

gs_small=0.002
#gs_small=0.05


proj=-JX-7/6
#proj=-JX-5l/4
#fs=""
ofile=px0k.ps
for i in 1 2 3 4;do
    #ofile=px0k.$i.ps
    if [ $i = 1 ];then
	ymin=-2.5;ymax=0.2
	reg=-R0.85/1.0005/$ymin/$ymax
	ann=-Ba0.02f0.002:"@~k@~'":/a0.5f0.05:y:
	#	gs=0.001
	gs=$gs_small
    elif [ $i = 2 ];then
	#ymin=-2.5;ymax=0.3
	ymin=-2.2;ymax=0.2
	#reg=-R0.8515/.8669/$ymin/$ymax
	reg=-R0.8516/.858/$ymin/$ymax
	#ann=-Ba0.001f0.0001g0.0001:"@~k@~'":/a0.5f0.05:y:
	ann=-Ba0.001f0.0001:"@~k@~'":/a0.5f0.05:y:
	#gs=0.1
	gs=$gs_small
    elif [ $i = 3 ];then
	#ymin=-2.2;ymax=-0.8
	#reg=-R0.8516/0.8555/$ymin/$ymax
	ymin=-1.9;ymax=-1.4
	reg=-R0.854/0.8555/$ymin/$ymax
	ann=-Ba0.0005f0.00005:"@~k@~'":/a0.1f.01:y:
	#gs=0.1
	gs=$gs_small
    else
	ymin=-1.645;ymax=-1.565
	#	reg=-R0.8548/0.8552/$ymin/$ymax
	#reg=-R0.8548/0.855/$ymin/$ymax
	reg=-R0.8549/0.85498/$ymin/$ymax
	ann=-Ba0.00002f0.000001:"@~k@~'":/a0.01f.001:y:
	#gs=0.1
	gs=$gs_small
    fi
    #ann=-Ba3f2:"@~k@~'":/a0.01f.001:y:
    if [ $i -eq 1 ];then
	psbasemap $reg $proj -K -P $ann"WesN" -Y7 > $ofile
    elif [ $i -eq 2 ];then
	psbasemap $reg $proj -K -O $ann"wEsN" -X7.25 >> $ofile
    elif [ $i -eq 3 ];then
	psbasemap $reg $proj -K -O $ann"WeSn" -X-7.25 -Y-6.5 >> $ofile
    elif [ $i -eq 4 ];then
	psbasemap $reg $proj -K -O $ann"wESn" -X7.25 >> $ofile
    fi
	
    if [[ $i -ge 1 ]];then
	for k in $ks;do
	    cat <<EOF | psxy $reg $proj -O -K -W.25,gray >> $ofile
$k $ymin
$k $ymax
EOF
	done
    fi
    for imode in $pimodes;do
	((c=imode+1))
	col=`platecolor $c`
	#col=`platecolor 1`
	echo $imode $c $col
	psxy $tmpn.$imode -Sc$gs -G$col $reg $proj -O -K >> $ofile
    done
    if [ $i -eq 4 ];then       # close
	echo 1000 1000 1 | psxy -Sc $reg $proj -O >> $ofile
    else
	echo 1000 1000 1 | psxy -Sc $reg $proj -O -K >> $ofile
    fi
    #modifybb $ofile 0
    #fs="$fs $ofile"
done
#epsmerge -y 2 -x 2 --orientation Landscape -par $fs > px0k.ps
psconvert -Tg -A+m0.1 px0k.ps
#modifybb px0k.ps 1
rm $fs px0k.ps tmp*
cp px0k.png $HOME/Dropbox/tmp/



