#!/bin/bash
#
# plot basins of attraction and Lyapunov exponents from run_basin_test
# output, one row per stiffness case (attractor type map, lambda_1 map)
#
# usage: plot_basins [prefix1] [prefix2] [ofile] [clip]
#
# each prefix refers to <prefix>.<rank>.dat files as written by
# basin_test and basin_rs2 a single-prefix plot results if prefix2 is an empty
# string. clip > 0 truncates the lambda_1 color scale at that value.
#
p1=${1-basin_08574}
p2=${2-basin_08577}
ofile=${3-basins}		# without .ps
lclip=${4-0}			# 0: automatic lambda_1 scale

tmpn=`mktemp`
trap "rm -f $tmpn*" EXIT

prefixes="basin_files/$p1"
if [ "X$p2" != "X" ];then
    prefixes="basin_files/$p1 basin_files/$p2"
fi

# panel layout
pwidth=4.5			# panel width 
proj=-JX$pwidth/$pwidth
dx=5.5				# panel offsets
dy=5.5

# collect data, determine common period levels and lambda range
np=0
allper=""
lmax=0
for p in $prefixes;do
    cat $p.*.dat | gawk '{if(substr($1,1,1)!="#")print($0)}' > $tmpn.$np.d
    # header for label
    knd[$np]=`gawk '{if($2=="knd"){print($3);exit}}' $p.0.dat`
    # period map: chaotic = -1, unclassified skipped
    gawk '{if($7==0)printf("%.12g %.12g %g\n",$1*1e3,$2*1e3,$6);
	   else if($7==1)printf("%.12g %.12g -1\n",$1*1e3,$2*1e3)}' \
	 $tmpn.$np.d > $tmpn.$np.per
    # lambda_1 map, scaled by 1e3, unclassified (e.g. fixed point) skipped
    gawk '{if($7!=2)printf("%.12g %.12g %.12g\n",$1*1e3,$2*1e3,$3*1e3)}' $tmpn.$np.d > $tmpn.$np.lam
    allper="$allper "`gawk '{print($3)}' $tmpn.$np.per | sort -g | uniq`
    lm=`gawk 'BEGIN{m=0}{if($3>m)m=$3}END{print(m)}' $tmpn.$np.lam`
    lmax=`echo $lmax $lm | gawk '{print(($1>$2)?$1:$2)}'`
    np=`expr $np + 1`
done
pvals=`echo $allper | tr ' ' '\n' | sort -g | uniq`
if [ `echo $lclip | gawk '{print(($1>0)?1:0)}'` -eq 1 ];then
    lmax=`echo $lclip | gawk '{print($1*1e3)}'`
fi
lann=`echo $lmax | gawk '{a=$1/3;e=10^int(log(a)/log(10));print(int(a/e+0.5)*e)}'`

# categorical CPT for attractor type; chaotic dark red, periods from a
# fixed palette so colors are consistent across panels
cols="0/114/178 0/158/115 230/159/0 204/121/167 86/180/233 240/228/66"
# contiguous slices with boundaries at category midpoints
echo $pvals | gawk -v cols="$cols" '{
  n=NF;for(i=1;i<=n;i++)v[i]=$i;
  nc=split(cols,c," ");ic=0;
  for(i=1;i<=n;i++){
    lo=(i==1)?v[1]-0.5:(v[i-1]+v[i])/2;
    hi=(i==n)?v[n]+0.5:(v[i]+v[i+1])/2;
    if(v[i]==-1)col="178/34/34";
    else{ic++;col=c[(ic-1)%nc+1];}
    lab=(v[i]==-1)?"chaotic":sprintf("period %i",v[i]);
    printf("%g\t%s\t%g\t%s\t;%s\n",lo,col,hi,col,lab);
  }}' > $tmpn.per.cpt
# continuous CPT for lambda_1
lmin=`gawk 'BEGIN{m=0}{if($3<m)m=$3}END{print(m)}' $tmpn.*.lam | sort -g | head -1`

gmt makecpt -Cinferno -T$lmin/$lmax/30+n -D > $tmpn.lam.cpt
#gmt makecpt -Cvik+h0 -T$lmin/$lmax/0.1 > $tmpn.lam.cpt


labels="a b c d e f g h"
first=1
ip=`expr $np - 1`
while [ $ip -ge 0 ];do
    # region and grid spacing from the data
    reg=`gmt gmtinfo -I- $tmpn.$ip.per`
    inc=`gawk '{print($1)}' $tmpn.$ip.per | sort -g | uniq | gawk '{if(NR==2)printf("%.12e\n",$1-x);x=$1}'`
    kl=`echo ${knd[$ip]} | gawk '{printf("%g",$1)}'`
    la=`echo $labels | gawk -v i=$ip '{print($(2*i+1))}'`
    lb=`echo $labels | gawk -v i=$ip '{print($(2*i+2))}'`

    # attractor type panel
    gmt xyz2grd $tmpn.$ip.per $reg -I$inc -G$tmpn.per.grd
    if [ $first -eq 1 ];then
	gmt grdimage $tmpn.per.grd $reg $proj -C$tmpn.per.cpt \
	    -Ba1f0.25:"@~e@~@-1@- [10@+-3@+]":/a1f0.25:"@~e@~@-2@- [10@+-3@+]":WeSn \
	    -X2.5 -Y4 -P -K > $ofile.ps
	gmt psscale -C$tmpn.per.cpt -D`echo $pwidth | gawk '{print($1/2)}'`/-1/4/0.4h -L0.1 -O -K >> $ofile.ps
    else
	gmt grdimage $tmpn.per.grd $reg $proj -C$tmpn.per.cpt \
	    -Ba1f0.25:"@~e@~@-1@- [10@+-3@+]":/a1f0.25:"@~e@~@-2@- [10@+-3@+]":WeSn \
	    -X-$dx -Y$dy -O -K >> $ofile.ps
    fi
    echo $reg | gawk -F/ '{gsub("-R","",$1);print($1,$4)}' | \
	gmt pstext $reg $proj -F+f18p+jTL+cTL+t"$la) @~k@~' = $kl" -D0.25/-0.25 \
	    -Gwhite -W0.5p -O -K >> $ofile.ps

    # lambda_1 panel
    gmt xyz2grd $tmpn.$ip.lam $reg -I$inc -G$tmpn.lam.grd
    gmt grdimage $tmpn.lam.grd $reg $proj -C$tmpn.lam.cpt \
	-Ba1f0.25:"@~e@~@-1@- [10@+-3@+]":/a1f0.25:"@~e@~@-2@- [10@+-3@+]":wESn \
	-X$dx -O -K >> $ofile.ps
    echo $reg | gawk -F/ '{gsub("-R","",$1);print($1,$4)}' | \
	gmt pstext $reg $proj -F+f18p+jTL+cTL+t"$lb)" -D0.25/-0.25 \
	    -Gwhite -W0.5p -O -K >> $ofile.ps
    if [ $first -eq 1 ];then
	gmt psscale -C$tmpn.lam.cpt -D`echo $pwidth | gawk '{print($1/2)}'`/-1/4/0.2h \
	    -Ba${lann}f`echo $lann | gawk '{print($1/2)}'`:"@~l@~@-1@- [10@+-3@+]": -O -K >> $ofile.ps
	first=0
    fi

    ip=`expr $ip - 1`
done
gmt psxy -T  -O >> $ofile.ps

modifybb $ofile.ps 1
echo $0: written to $ofile.pdf

