#!/bin/bash
# analyze the minority basin strucutre
#
# run run_basin_test first
#
# large, zoom, double zoom
models="basin_files/b74e basin_files/b77e basin_files/b74e_513z basin_files/b77e_513z basin_files/b74e_513zz  basin_files/b77e_513zz  basin_files/b74e_patch basin_files//b74e_patch90  basin_files//b74e_patch90d"


python3 basin_analyze.py  $models > balog.dat

python3 basin_boxcount.py $models > bclog.dat


