#!/bin/bash
ks=${1-"all"}			# value or "all" 0.8577 
inits=${2-"1 2 3"}		# directions
eps_dx=${3-0.025}		# spacing
use_exp_solve=${4-1}

tmpn=`mktemp`
trap "rm -f $tmpn*" EXIT

if [ $ks = "all" ];then
    #ks=`gawk 'BEGIN{for(x=0.8571;x<=0.8580;x+=0.0000025)print(x)}'`
    ks=`gawk 'BEGIN{for(x=0.8573;x<=0.8579;x+=0.000001)print(x)}'`
fi
echo $ks | wc

epss=`gawk -v dx=$eps_dx 'BEGIN{x=-9;while(x<=1){print(10**x);x+=dx;}}' `

echo $epss | wc
#echo $ks
#echo $epss

tmpn=`mktemp`
trap "rm -f $tmpn*" EXIT

rm twe.$init.$$.log 2> /dev/null

tc=0
for k in $ks;do
    for init in $inits;do
	if [ -s twe.$init.log ];then
	    cp twe.$init.log $tmpn.old
	fi
	for eps in $epss;do
	    if [ -s $tmpn.old ];then
		nold=`gawk -v k=$k -v e=$eps -v u=$use_exp_solve '{if($1==k)if($4==e)if($5==u)print($0)}' $tmpn.old | lc`
	    else
		nold=0
	    fi
	    if [ $nold -eq 0 ];then
		echo $0: running for init $init k $k e $eps ues $use_exp_solve
		(find_intersect $k 1 $init $eps $use_exp_solve > $tmpn.$init.$k.$eps.log ) &
		((tc=tc+1))
		if [ $tc -ge $NR_CPUS ];then
		    wait
		    cat $tmpn.*.log  >> twe.$init.$$.log
		    rm  $tmpn.*.log
		    tc=0
		fi
	    else
		echo $0: found $nold for init $init k $k e $eps ues $use_exp_solve
	    fi
	done
    done
done
wait
cat $tmpn.*.log  >> twe.$init.$$.log
rm  $tmpn.*.log

#sort twe.$init.log | uniq > tmp.$$; mv tmp.$$ twe.$init.log
cat twe.$init.$$.log >> twe.$init.log
rm twe.$init.$$.log
