#!/bin/bash
laws="aging slip prz sato kt"
eps=1e-6
ofile=slider.ps

reg=-R200/270/-16/1
proj=-JX7/4
#
# vel vs time for 3bs and IMEX solves
#
psbasemap $reg $proj -Y10 -K -P -Ba10f2:"time [years]":/a2f.5:"@~\341@~log@-10@-(v [m/s])@~\361@~": > $ofile
pc=1;
yl=0;xl=202
for sl in $laws ;do
    col=`platecolor $pc`
    gawk '{if(NR>1)print($3,$5)}' "results/"$sl"_5dp_"$eps"/rsf_monitor.dat" | \
	psxy -W2,$col,- $reg $proj -O -K >> $ofile
    gawk '{if(NR>1)print($3,$5)}' "results/"$sl"_3bs_"$eps"/rsf_monitor.dat" | \
	psxy -W1,$col $reg $proj -O -K >> $ofile
    gawk '{if(NR>1)print($3,$5)}' "results/"$sl"_imex_"$eps"/rsf_monitor.dat" | \
	psxy -W3,$col,. $reg $proj -O -K >> $ofile
    echo $xl $yl 18 0 29 LM $sl | pstext -R -J -O -K -F+f$col >> $ofile
    ((yl=yl-2))
    ((pc=pc+1))
done
pc=1;xl=-15.5;yl=0.67
reg=-R-16/1/0.52/0.69		# phase space
psbasemap $reg $proj -Y-5 -K -O -Ba2f.5:"@~\341@~log@-10@-(v [m/s])@~\361@~":/a.05f0.005:"friction @~m@~": >> $ofile
for sl in $laws ;do
    col=`platecolor $pc`
    gawk '{if(NR>1)if($3>300)print($5,$7)}' "results/"$sl"_3bs_"$eps"/rsf_monitor.dat" | \
	psxy -W1,$col $reg $proj -O -K >> $ofile
    echo $xl $yl 18 0 29 LM $sl | pstext -R -J -O -K -F+f$col >> $ofile
    yl=$(bc <<< "$yl - 0.025")
    ((pc=pc+1))
done

psxy -T -O >> $ofile
modifybb $ofile 1
