#!/bin/bash
#
# reads flt patch geometry and slip from flt.dat and geom.in
#
gfile=${1-geom.in}
fsfile=${2-flt.dat}
type=${3-3} # strike: 1 dip: 2 abs: 3

if [[ ! -s $gfile || ! -s $fsfile ]];then
    echo $0: $gfile or $fsfile not found
    exit
fi

# extract center of patches
gawk '{if($1!="")print($1,$2,$3)}' $gfile > tmp.$$.xyz
minmax tmp.$$.xyz

# extract corners and vectors
cat $gfile | patch2xyzvec > tmp.$$.cvec 2> /dev/null

scale=0.001

# extract slip: strike, dip, normal
gawk '{if((substr($1,1,1)!="#")&&(NF>8))print($6/s,$8/s,$7/s,sqrt($6*$6+$8*$8+$7*$7)/s)}' \
    s=$scale $fsfile > tmp.$$.slip
minmax -C tmp.$$.slip  > tmp.$$.dat
read min1 max1 min2 max2 min3 max3 < tmp.$$.dat ; rm tmp.$$.dat

absslipmax=`gawk '{print($4)}' tmp.$$.slip | minmax  -C  | gawk '{print($2)}'`
if [[ `lc tmp.$$.xyz` -ne `lc tmp.$$.cvec`  \
    || `lc tmp.$$.cvec` -ne `lc tmp.$$.slip` ]];then
    echo $0: length mismatch
    exit
fi

#reg=-R-1/1/-1/1/-1/0
#ann=-Ba.5f.1/a.5f.1:"[10 km]":/a.5f.1WeSnZ+
#proj="-Jx3 -Jz3 -E200/25"

#reg=`minmax tmp.$$.xyz -I1`/-30/0
reg=`minmax tmp.$$.xyz -I1`/-40/0
#ann=-Ba100f10:"west-east [km]":/a100f10:"north-south [km]":/a20f2WESNZ+
ann=-Ba10f1:"west-east [km]":/a10f1:"north-south [km]":/a10f1:"depth [km]":WESNZ+
#proj="-Jx0.02 -Jz0.02 -E210/30"
proj="-Jx.1 -Jz.1 -E50/30"

#cmp=haxby
cmp=roma
if [ $type -eq 1 ];then		# strike
    echo $min1 $max1  | gawk  '{printf("-T%g/%g/%g %f",$1,$2,($2-$1)/15,($2-$1)/3)}' > tmp.$$.dat
    read tstring ls < tmp.$$.dat ; rm tmp.$$.dat
    makecpt $tstring -I -C$cmp > tmp.cpt
    #makecpt -T-0.04/0.04/0.005 -C$cmp > tmp.cpt
    #makecpt -T-2000/2000/100 -C$cmp > tmp.cpt;ls=500
    use=22
    label="u@-strike@-"
    ends=-E
elif [ $type -eq 2 ];then	#  dip
    ends=-E
    makecpt -T-0.4/0.4/0.05 -C$cmp > tmp.cpt
    use=23
    ls=0.2
    label="u@-dip@-"
elif [ $type -eq 3 ];then	# total
    echo $absslipmax
    makecpt -T0/$absslipmax/0.1 -I -C$cmp > tmp.cpt
    #makecpt -T0/0.05/.001 -C$cmp > tmp.cpt;ls=0.025
    #makecpt -T0/1/0.01 -C$cmp > tmp.cpt 
    use=25
    ls=0.5
    label="u@-abs@-"
    ends=-Ef
fi
ofile=slip.3d.$type.ps
# slip is strike, dip, normal
paste tmp.$$.cvec tmp.$$.slip | \
# cvec x1 y1 z1 x2 y2 z2 x3 y3 z3 x4 y4 z4 sx sy sz dx dy dz nx ny nz  strike dip normal abs
#      1        4        7        10       13       16       19    21    22   23  24     25
#gawk '{printf("> -Z%g -W0.1\n",$(use));\
gawk '{printf("> -Z%g \n",$(use));\
    print($1,$2,$3);print($4,$5,$6);\
    print($7,$8,$9);print($10,$11,$12);}' use=$use | \
    psxyz $reg $proj -P -L -m  -Ctmp.cpt \
	  "$ann"  -K > $ofile
echo $ls
psscale -Ctmp.cpt -Dx3/.25/3/.2h $ends -B$ls/:"$label": -O >> $ofile
echo $0: output in $ofile

modifybb $ofile    

rm tmp.$$.cvec tmp.$$.slip tmp.$$.xyz tmp.cpt 2> /dev/null

