#!/bin/ksh
case=${1-1}
mode=${2-1}
klim1=${3--1.0e-8}
klim2=${4-1.0e-8}
infile=flt_stress.$case.out
if [ $mode -eq 1 ]
then
    i=1
    j=2
    k=3
    l1='x'
    l2='y'
    l3='z'
fi
if [ $mode -eq 2 ]
then
    i=1
    j=3
    k=2
    l1='x'
    l2='z'
    l3='y'
fi
if [ $mode -eq 3 ]
then
    i=2
    j=3
    k=1
    l1='y'
    l2='z'
    l3='x'
    
fi
klevel=`echo $klim1 $klim2 | awk '{print(($1+$2)/2.0)}'`
adjust=0
adjustcolor=0
proj="-JX3.5 -P"
ofile=fstress.$case.$mode.ps
cmap=stress.cpt
echo $0: mode $mode, $l3 is zero, klim1: $klim1 klim2: $klim2 klevel: $klevel
echo $0: reading from $infile
if [ ! -s $infile ]
then
    echo $0: $infile is not there
    exit
fi
echo  0 A > cont.d
if [ $adjust -eq 1 ]
then
    n=90
    xmin=`nawk -f $HOME/idl_gmt/min.awk col=$i $infile` 
    xmax=`nawk -f $HOME/idl_gmt/max.awk col=$i $infile` 
    ymin=`nawk -f $HOME/idl_gmt/min.awk col=$j $infile` 
    ymax=`nawk -f $HOME/idl_gmt/max.awk col=$j $infile` 
    reg=-R$xmin/$xmax/$ymin/$ymax
    inc=-I`echo $xmin $xmax $ymin $ymax | awk '{xr=$2-$1;yr=$4-$3;if(yr>xr)print(yr/n); else print(xr/n)}' n=$n` 
    ann=`echo $xmin $xmax $ymin $ymax | awk '{xr=$2-$1;yr=$4-$3;if(yr>xr)print(yr/10); else print(xr/10)}'`
else
    if [ $mode -eq 1 ]
    then
	reg=-R-5/5/-5/5
    else
	reg=-R-5/5/-10/0
    fi
    inc=-I0.2
    ann=1
fi

echo $0: region $reg inc $inc annotation $ann
echo $0: gridding...
cat $infile | \
    awk '{if($4*$4<1e10 && $k<klim2 && $k>klim1)
	print($i,$j,$4);}' i=$i j=$j k=$k klim1=$klim1 klim2=$klim2 | \
	surface $reg $inc -Gst.grd 

cat $infile | \
    awk '{if($5*$5<1e10 && $k<klim2 && $k>klim1)
	print($i,$j,$5);}' i=$i j=$j  k=$k klim1=$klim1 klim2=$klim2 | \
	surface $reg $inc -Gsd.grd 
cat $infile | \
    awk '{if($6*$6<1e10 && $k<klim2 && $k>klim1)
	print($i,$j,$6);}' i=$i j=$j  k=$k klim1=$klim1 klim2=$klim2 | \
	surface $reg $inc -Gsn.grd 
echo $0: plotting...

if [ $adjustcolor -eq 1 ]
then
    grd2cpt st.grd > $cmap
    grd2cpt sd.grd > $cmap
    grd2cpt sn.grd > $cmap
else
    makecpt -Cjet -T-1/1/.1 > $cmap

fi
grdimage st.grd -X0.75 -C$cmap $reg $proj -P -Ba$ann:$l1/"strike":/a$ann:$l2:WeSn -K > $ofile
grdcontour st.grd -Ccont.d  -O -K $reg $proj >> $ofile 
awk -f $HOME/idl_gmt/geom2xyz.awk i=$i j=$j  geom.$case.in | \
    psxy  -M -W5/255/0/0 -O  $reg $proj -K -V >> $ofile 


grdimage sd.grd -C$cmap $reg $proj -P -Ba$ann:$l1/"dip":/a$ann:$l2:wEsN:.$l3=$klevel: \
    -O -Y2.5 -X3.75 -K >> $ofile
grdcontour sd.grd -Ccont.d  -O -K $reg $proj >> $ofile 
awk -f $HOME/idl_gmt/geom2xyz.awk i=$i j=$j  geom.$case.in | \
    psxy  -M -W5/255/0/0 -O  $reg $proj -K -V >> $ofile 


grdimage sn.grd -C$cmap $reg $proj -P -Ba$ann:$l1/"normal":/a$ann:$l2:WesN \
    -O -Y2.5 -X-3.75 -K >> $ofile
grdcontour sn.grd -Ccont.d  -O  $reg $proj -K >> $ofile 
awk -f $HOME/idl_gmt/geom2xyz.awk i=$i j=$j  geom.$case.in | \
    psxy  -M -W5/255/0/0 -O  $reg $proj -K -V -O >> $ofile 

rm sn.grd st.grd sd.grd
echo $0: written to $ofile
