#!/bin/ksh
l=3
infile=${1-geom}
includepoints=${2-0}
fixedrange=${3-0}
testcircle=${4-0}
usethree=0

if [ ! -s $infile.in ];then
    echo $0: can not find $infile.in
    exit
fi
cat $infile.in | patch2xyz > tmp.xyz
exit
file=$infile.2d.ps

if [ $fixedrange -eq 0 ];then
    xmin=`gawk -f min.awk col=1 $infile.in` 
    xmax=`gawk -f max.awk col=1 $infile.in ` 
    ymin=`gawk -f min.awk col=2 $infile.in ` 
    ymax=`gawk -f max.awk col=2 $infile.in ` 
    zmin=`gawk -f min.awk col=3 $infile.in ` 
    zmax=0 
    ann1=-Bf10a100:x:/f10a100:y:SWen

else
    ann1=-Bf1a2g1:x:/f1a2g1:y:SWen
    bound=2
    xmin=-$bound
    xmax=$bound
    ymin=-$bound
    ymax=$bound
    zmin=-2.
    zmax=0

fi

ann2=-Bf1a2:y:/f1a2:z:SEnw
ann3=-Bf1a2:x:/f1a2:z:WNse
scl=0.3
reg1=-R$xmin/$xmax/$ymin/$ymax
reg2=-R$ymin/$ymax/$zmin/$zmax
reg3=-R$xmin/$xmax/$zmin/$zmax

proj="-JX7 -P"



gawk '{print($1,$2)}' tmp.xyz  | 
    psxy $reg1 $ann1  -m $proj -K  -W1,darkgreeen > $file

if [ $usethree -eq 1 ];then
    if [ ! $testcircle -eq 1 ]
    then
	gawk '{if($1==">")print(">"); else print($2,$3)}' tmp.xyz  | \
	    psxy  $reg2 $ann2 -L -m $proj -O -Y2 -X4 -K \
	    -Gdarkred -W3,blue >> $file
    else
	gawk '{if($1==">")print(">"); else print($2,$3)}' tmp.xyz  | \
	    psxy  $reg2 $ann2 -L -m $proj -O -Y2 -X4 -K \
	    -Gdarkred  >> $file
	gawk 'BEGIN{for(x=0.0;x<=6.283185307179586476925286;x+=0.01)\
	    print(cos(x),sin(x)-1)}' | \
	    psxy  $reg2  $proj -O -K  -W2,darkgreen >> $file
      
    fi
    gawk '{print($1,$3)}' tmp.xyz  | \
	psxy  $reg3 $ann3 -L -m $proj -O  -Y2 -X-4 -Gdarkred -W3,blue  >> $file
else
    psxy -T $reg1  $proj -O  >> $file
fi

modifybb $file

rm tmp.xyz
