#!/bin/bash
infile=${1-geom}
includepoints=${2-0}
fixedrange=${3-0}
testcircle=${4-0}
usethree=0

if [ ! -s $infile.in ];then
    echo $0: can not find $infile.in
    exit
fi
cat $infile.in | patch2xyz > tmp.xyz
cat $infile.in | patch2xyz xx 0 1 > tmp.s.xyz

file=$infile.2d.ps

if [ $fixedrange -eq 0 ];then
    minmax -C tmp.xyz > tmp.dat
    read xmin xmax ymin ymax zmin zmax < tmp.dat ; rm tmp.dat
    ann1=-Bf.5a5:x:/f.5a5:y:SWen

else
    ann1=-Bf1a2g1:x:/f1a2g1:y:SWen
    bound=2
    xmin=-$bound;xmax=$bound
    ymin=-$bound;ymax=$bound
    zmin=-2.;zmax=0

fi

ann2=-Bf1a2:y:/f1a2:z:SEnw
ann3=-Bf1a2:x:/f1a2:z:WNse
reg1=-R$xmin/$xmax/$ymin/$ymax
reg2=-R$ymin/$ymax/$zmin/$zmax
reg3=-R$xmin/$xmax/$zmin/$zmax

proj="-Jx.2 -P"
#
#psxy tmp.xyz $reg1 $ann1  -m $proj -K  -W1,darkgreen > $file
# shrunk patches
psxy tmp.s.xyz $reg1 $ann1  -m $proj -K  -W1,darkgreen > $file

if [ $usethree -eq 1 ];then
    if [ ! $testcircle -eq 1 ]
    then
	gawk '{if($1==">")print(">"); else print($2,$3)}' tmp.xyz  | \
	    psxy  $reg2 $ann2 -L -m $proj -O -Y2 -X4 -K \
	    -Gdarkred -W3,blue >> $file
    else
	gawk '{if($1==">")print(">"); else print($2,$3)}' tmp.xyz  | \
	    psxy  $reg2 $ann2 -L -m $proj -O -Y2 -X4 -K \
	    -Gdarkred  >> $file
	gawk 'BEGIN{for(x=0.0;x<=6.283185307179586476925286;x+=0.01)\
	    print(cos(x),sin(x)-1)}' | \
	    psxy  $reg2  $proj -O -K  -W2,darkgreen >> $file
      
    fi
    gawk '{print($1,$3)}' tmp.xyz  | \
	psxy  $reg3 $ann3 -L -m $proj -O  -Y2 -X-4 -Gdarkred -W3,blue  >> $file
else
    psxy -T $reg1  $proj -O  >> $file
fi

modifybb $file

rm tmp.xyz tmp.s.xyz
