#!/bin/bash
dir=${1-.}
if [[ ! -s $dir/geom.in || ! -s $dir/events.bin ]];then
    echo $0: file error
    exit
else
    echo $0: using $dir/geom.in and $dir/events.bin
fi

sdir=/tmp/interact.events

rm $sdir.*.gmt 2> /dev/null

cd $dir 
read_bin_events
cd -
#exit
cat $dir/geom.in | patch2xyz > tmp.xyz
reg=-R150/530/5015/5250/-30/0
pscale=0.01
proj="-Jx$pscale  -Jz0.015 -E130/30"

makecpt -T-1/3/.5 -Qi -I -Croma > mom.cpt


fs=""
i=0;j=0
n=`ls $sdir.*.gmt | lc`
#n=4
while [ $i -lt $n ];do
    il=`echo $i | gawk '{printf("%06i",$i)}'`
    tlabel=`head -1 $sdir.$il.gmt | gawk '{printf("%02.4f",$3)}'`
    ofile=$sdir.$il.ps
    ( psxyz tmp.xyz $reg $proj -m   -L -Cmom.cpt -P -K -Ggray  > $ofile;psxyz $sdir.$il.gmt $reg $proj -m  -L -O  -Cmom.cpt -Ba100f20:x:/a100f20:y:/a20f5:z::.$tlabel:WESNZ+  >> $ofile;psconvert -Tg -A+m0.1 $ofile; rm $ofile;/usr/bin/convert -density 75 $sdir.$il.png $sdir.$il.gif;rm $sdir.$il.png ) &
    fs="$fs $sdir.$il.gif"
    echo $sdir.$il.gif
    if [ $j -ge $NR_CPUS ];then
	wait
	j=0
    fi
    ((j=j+1))
    ((i=i+1))
done
wait
gifsicle --colors 256 $fs > $dir/event_movie.gif
rm $fs $sdir.*.gmt
