#!/bin/ksh
#
# plot spectral power of seismicicty with time
#
tmpnl=/tmp/tmp.$$
awk '{if($1>10)print($1,$3)}' cevents.dat | \
	mspectral -0.02 -0.2 0.125 > $tmpn.dat
#gawk -f minmax.awk col=3 $tmpn.dat > $tmpn.max
#read fmin fmax < $tmpn.max

fmin=0
fmax=2.5
df=`echo $fmin $fmax | awk '{print(($2-$1)/63.0)}'`
echo $fmin $fmax $df
surface $tmpn.dat -R$fmin/$fmax/0/1 -I$df/0.01 -Gspec.grd -Lld -Lud
makecpt -Chot -T0/30/1 -Z > spec.cpt
grdimage spec.grd -Cspec.cpt -P -Ba0.2f0.1:"frequency":/a0.2f0.1WeSn:"time": \
    -JX7 > spec.ps

rm spec.grd
rm spec.cpt

rm $tmpn.*
