#
# flags for PETSC support - this can be compiled without any HMAT support if need be
# and using petsc H matrix packages HTOOLS and H2OPUS or external interfaces HMMVP and HACApK
#
# the 32 bit versions work with Htools and H2OPUS
# PETSC_ARCH = arch-linux-c-opt
PETSC_HTOOL_USED=-DUSE_PETSC_HMAT
#
# debug 32 bit version
#PETSC_ARCH = arch-linux-c-debug
#PETSC_HTOOL_USED=-DUSE_PETSC_HMAT
#
# the 64 bit integer evrsion does not have H matrices
#PETSC_ARCH = arch-linux-c-opt64
#PETSC_HTOOL_USED=

# config files
FILE1 := $(PETSC_DIR)/$(PETSC_ARCH)/lib/pkgconfig/PETSc.pc # default
FILE2 := $(PETSC_DIR)/lib/pkgconfig/PETSc.pc # fallback

PETSc.pc := $(if $(wildcard $(FILE1)),$(FILE1),$(FILE2))

# Additional libraries that support pkg-config can be added to the list of PACKAGES below.
PACKAGES := $(PETSc.pc)

CC := $(shell pkg-config --variable=ccompiler $(PACKAGES))
CXX := $(shell pkg-config --variable=cxxcompiler $(PACKAGES))
FC := $(shell pkg-config --variable=fcompiler $(PACKAGES))
SCARGS_OTHER := $(shell pkg-config --cflags-only-other $(PACKAGES))
SCARGS := $(shell pkg-config --variable=cflags_extra $(PACKAGES)) $(CFLAGS_OTHER)
CXXFLAGS := $(shell pkg-config --variable=cxxflags_extra $(PACKAGES)) $(CFLAGS_OTHER)
SFARGS := $(shell pkg-config --variable=fflags_extra $(PACKAGES)) 

CPPFLAGS := $(shell pkg-config --cflags-only-I $(PACKAGES))
PETSC_LDIR := $(shell pkg-config --libs-only-L --libs-only-other $(PACKAGES))
PETSC_LDIR += $(patsubst -L%, $(shell pkg-config --variable=ldflag_rpath $(PACKAGES))%, $(shell pkg-config --libs-only-L $(PACKAGES)))
PETSC_LIBADD := $(shell pkg-config --libs-only-l $(PACKAGES)) -lm
#
# leave empty if not using HACAPK
#HACAPK_LIBS =
#HACAPK_DEFINES =
# optional HACApK support for compress_interaction_matrix: build the
# C interface library first (cd HACApK/v.1.0.0/C_interface; make; 
# ar rcs libhacapk.a m_*.o HACApK_*.o) then uncomment:
HACAPK_DEFINES = -DUSE_HACAPK
HACAPK_LIBS = -L./HACApK/v.1.0.0/C_interface -lhacapk -lgfortran -fopenmp $(MATHLIBS)

#
# leave empty if not using
#HMMVP_LIBS =
#HMMVP_OBJS =
#HMMVP_DEFINES =
#HMMVP_INC =
# optional hmmvp support for compress_interaction_matrix
# (https://github.com/ambrad/hmmvp, build there with -std=c++14 in
# opt, mode=omp, and mkdir lib bin; see compress_interaction_matrix.md)
#
# hmmvp build-mode flag for the C++ shim; MUST match the linked library:
#   libhmmvp_mpi -> -DUSE_HMMVP_MPI     (MpiHmat path; pure MPI)
#   libhmmvp_omp -> -fopenmp   (in-memory Hmat path)
# the shim (hmmvp_c_shim.cpp) selects MpiHmat vs in-memory Hmat on USE_HMMVP_MPI,
# so this must be passed to its compile rule (see makefile)
HMMVP_DIR = ./hmmvp/
HMMVP_DEFINES = -DUSE_HMMVP -DUSE_HMMVP_MPI
HMMVP_INC = -I$(HMMVP_DIR) -I$(HMMVP_DIR)/hmmvp/include -I$(HMMVP_DIR)/util/include
HMMVP_LIBS = -L$(HMMVP_DIR)/lib -lhmmvp_mpi -lstdc++ $(MATHLIBS)
HMMVP_OBJS = $(ODIR)/hmmvp_c_shim.o
#
# BigWham (use_hmatrix 5): native FULL-SPACE hierarchical matrix backend.
# OFF by default (BigWham is GPL v3, OpenMP-only, and not part of interact).
# To enable: clone https://github.com/GeoEnergyLab-EPFL/BigWham into
# interact/BigWham, build it with BigWham/compile_for_interact.sh, then
# uncomment the BIGWHAM_* lines below (and, if cblas.h is not on the default
# include path, add its directory to BIGWHAM_INC, e.g. on Debian/Ubuntu
# -I/usr/include/x86_64-linux-gnu). Leave empty to build without BigWham.

BIGWHAM_DIR = ./bigwham/BigWham/
ifeq ($(wildcard $(BIGWHAM_DIR)/.),) # does NOT exist
     BIGWHAM_DEFINES =
     BIGWHAM_INC =
     BIGWHAM_LIBS =
     BIGWHAM_OBJS =
else
     BIGWHAM_DEFINES = -DUSE_BIGWHAM
     BIGWHAM_INC = -I$(BIGWHAM_DIR)/src -I$(BIGWHAM_DIR)/il -DBIGWHAM_OPENMP -DIL_BLAS -DIL_OPENBLAS -DIL_OPENMP
     # those are slightly different from our MATHLIBs - do we worry?
     BIGWHAM_LIBS = $(BIGWHAM_DIR)/build/libBigWham.a -lopenblas -llapacke -lstdc++ -lgomp -lpthread $(MATHLIBS)
     BIGWHAM_OBJS = $(ODIR)/bigwham_shim.o
endif


PETSC_INCLUDES = -I$(PETSC_DIR)/include/ $(CPPFLAGS) 
#
#
PETSC_LIBS = -L$(PETSC_DIR)/lib/  $(PETSC_LDIR) $(PETSC_LIBADD)  

MPICC = $(shell pkg-config --variable=ccompiler $(PACKAGES))
MPICXX = $(shell pkg-config --variable=cxxcompiler $(PACKAGES))
MPILD =  $(shell pkg-config --variable=fcompiler $(PACKAGES))


# fallback if PETSc was built without fortran (--with-fc=0): fcompiler is empty
ifeq ($(strip $(MPILD)),)
MPILD = mpif77
endif

PETSC_DEFINES = -DUSE_PETSC $(PETSC_HTOOL_USED) $(HMMVP_DEFINES) $(HACAPK_DEFINES) $(BIGWHAM_DEFINES) 
