#!/bin/bash
#
# H-matrix solve of the UCERF strike-slip -> strike-stress operator
# with compress_interaction_matrix: x = A_H^-1 b for b = 1 on all
# patches, i.e. the same system as the dense interact solve in
# ../load_test/run_model (bc code 10, value 1). the H solution is
# written to flt.dat by compress_interaction_matrix and can be compared
# to the interact result.
#
# usage: run_test [ncore] [modes] [geometry] [rtol] [rfac] [backend]
#
#   ncore    MPI ranks (2)
#   modes    space separated list of modes, or "all" (all)
#   geometry geometry file name without .in (test)
#   rtol     KSP relative tolerance (1e-6)
#   rfac     near-field radius in mean patch lengths (4)
#   backend  H-matrix backend options, quoted (hmmvp, block-relative 1e-3)
#
# modes:
#   1  fgmres(2000), no preconditioner            (long restart, as before)
#   2  gmres(30),    no preconditioner            (PETSc default, stagnates on fault networks)
#   3  gmres(30),    near-field PC, ASM / sub LU  (proposed)
#   4  bcgs,         near-field PC, ASM / sub LU
#
# NOTE: the solve that produces flt.dat uses the KSP with options
# prefix "htool_" (all backends), so solver options have to be given as
# -htool_ksp_type etc.; un-prefixed -ksp_* options only affect the
# optional -nsolve timing solves with random right-hand sides, which
# are not run here. -skip_dense: no dense reference is built, so no
# error check against the dense operator is done; use a smaller
# geometry without -skip_dense for that.
#
# output per mode: log.<mode>.dat, flt.<mode>.dat, and a line in
# summary.dat (iterations, timings, slip difference to the first mode
# run and, if present, to ../load_test/flt.<refmode>.dat from run_model).
#
ncore=${1-2}
modes=${2-all}
g=${3-test}
rtol=${4-1e-6}
rfac=${5-4}
backend=${6-"-use_hmatrix 4 -hmmvp_inorm 1 -hmmvp_tol 1e-3"}

maxit=20000
bin=compress_interaction_matrix	# assumed in PATH
dense_ref=../load_test/flt.3.dat	# interact solution to compare with, if it exists

if [ ! -s $g.in ];then
    echo $0: geometry file $g.in not found
    exit 1
fi
if [ "$modes" = "all" ];then
    modes="1 2 3 4"
fi
export OMP_NUM_THREADS=1

rnear=$(gawk -v f=$rfac '{s+=2*$6;n++}END{printf("%g",f*s/n)}' $g.in)
npatch=$(gawk 'END{print NR}' $g.in)
echo $0: $npatch patches, near-field radius $rnear \($rfac patch lengths\), backend: $backend

common="-geom_file $g.in -skip_dense -nrandom 0 -nsolve 0 -test_forward 0"
monitor="-htool_ksp_converged_reason -htool_ksp_monitor_true_residual -htool_ksp_norm_type unpreconditioned -htool_ksp_rtol $rtol -htool_ksp_max_it $maxit"

if [ ! -s summary.dat ];then
    echo "# mode ncore npatch rtol its reason hmat_assembly_s solve_cpu_s total_s dense_ratio rel_slip_diff_to_ref ref_mode rel_slip_diff_to_dense settings" > summary.dat
fi
ref=""
for mode in $modes;do
    case $mode in
	1) options="-htool_ksp_type fgmres -htool_ksp_gmres_restart 2000 -htool_pc_type none";;
	2) options="-htool_ksp_type gmres -htool_pc_type none";;
	3) options="-htool_ksp_type gmres -near_pc_radius $rnear -htool_pc_type asm -htool_sub_pc_type lu";;
	4) options="-htool_ksp_type bcgs  -near_pc_radius $rnear -htool_pc_type asm -htool_sub_pc_type lu";;
	*) echo $0: mode $mode undefined; continue;;
    esac
    log=log.$mode.dat
    echo $0: mode $mode: $options
    t0=$(date +%s.%N)
    mpirun -bind-to core -np $ncore $bin $common $backend $options $monitor > $log 2>&1
    rc=$?
    t1=$(date +%s.%N)
    total=$(gawk -v a=$t0 -v b=$t1 'BEGIN{printf("%.1f",b-a)}')
    if [ $rc -ne 0 ];then
	echo $0: mode $mode: $bin returned $rc, see $log
	continue
    fi
    mv flt.dat flt.$mode.dat
    tasm=$(gawk '/hmat_assembly backend/{print $NF}' $log)
    tsol=$(gawk '/inverse solves/{for(i=1;i<=NF;i++)if($i ~ /s$/ && $(i-1)=="took"){sub("s","",$i);print $i}}' $log)
    ratio=$(gawk '/report_hmat_storage/{for(i=1;i<=NF;i++)if($i=="dense_ratio")print $(i+1)}' $log)
    its=$(gawk '/Linear htool_ solve/{print $NF}' $log)
    reason=$(gawk '/Linear htool_ solve/{print $(NF-2)}' $log)
    # reference for slip differences: mode 1 if its solution exists
    # (possibly from an earlier call), else the first mode of this run
    if [ -z "$ref" ];then
	if [ -s flt.1.dat ];then ref=1; else ref=$mode; fi
    fi
    # relative L2 difference of the strike slip (column 6 of flt.dat) to the reference
    diff=$(paste flt.$ref.dat flt.$mode.dat | gawk '$1!~/^#/{d=$6-$19;s+=d*d;r+=$6*$6}END{printf("%.3e",sqrt(s/r))}')
    if [ -s $dense_ref ];then
	ddiff=$(paste $dense_ref flt.$mode.dat | gawk '$1!~/^#/{d=$6-$19;s+=d*d;r+=$6*$6}END{printf("%.3e",sqrt(s/r))}')
    else
	ddiff="-"
    fi
    echo "$mode $ncore $npatch $rtol $its $reason $tasm $tsol $total $ratio $diff $ref $ddiff \"$backend $options\"" >> summary.dat
    echo $0: mode $mode: $its iterations \($reason\), H assembly $tasm s, solve $tsol s, total $total s, ratio $ratio, slip diff to mode $ref: $diff, to dense: $ddiff
    ./plot_sol $g flt.$mode
done
echo $0: summary in summary.dat
