#!/bin/bash
ks=${1-"0.88 0.86 0.856 0.8552 0.8525"}

for k in $ks;do
    kf=`echo $k | awk '{printf("state.%020.16f.dat",$1)}'`
    #sopt=""
    sopt="-atol 1e-5 -rtol 1e-8"
    # default, works
    popt="$sopt"
    #
    # 8vr, does not  work
    #popt="-ts_type rk -ts_rk_type 8vr $sopt"
    #
    # with inf norm, does not work
    #popt="-ts_type rk -ts_rk_type 8vr  -ts_adapt_wnormtype infinity $sopt"
    rm  $kf > /dev/null
    bin/ode_solve_test $popt 	    -knd $k
    if [[ ! -s $kf || `wc -l $kf | awk '{print($1)}'` -lt 1000 ]];then
	echo $0: solver error for $k
	exit
    fi
done


