#!/bin/bash

reg=-R-2/3/-2/0.2/-2/0.5
xscale=1;yscale=2;zscale=1.5
proj="-Jx$xscale/$yscale -Jz$zscale  -E130/30"



fs=""
for k in 0.88 0.86 0.856 0.8552 0.8525;do
    ann=-Ba1f.1:"x":/a1f.1:"y":/a1f.1:"z":WESNZ:."k = $k":
    kf=`echo $k | gawk '{printf("state.%020.16f.dat",$1)}'`
    if [ ! -s $kf ];then
	bin/ode_solve_test -knd $k
    else
	echo $0: reusing $kf
    fi

   
    ofile=tmp.$k.ps
    psbasemap $reg "$ann" $proj -K -P > $ofile
    gawk '{if($1>1e4)print($2,$3,$4)}' $kf | \
	psxyz $reg $proj -W0.5,blue -O >>$ofile
    modifybb $ofile
    #gv $ofile;exit
    fs="$fs $ofile"
    
done
epsmerge -par -x 2 -y 3 $fs > comp.ps
modifybb comp.ps 1
rm $fs 

