#!/bin/bash
run=${1-0}
plot=${2-0}

if [ $run -eq 1 ];then
    rm px0log.dat 2> /dev/null
    for k in `gawk 'BEGIN{for(k=1;k>=0.8515;k-=0.00005)print(k)}'`;do
	popt=""
	f=`echo $k | gawk '{printf("zero.%020.15f.dat",$1)}'`
	rm $f 2> /dev/null
	bin/ode_solve_test $popt -t_final 1e5 -knd $k > /dev/null 2> /dev/null
	if [  -s $f ];then
	    gawk '{printf("%.4f\n",$3)}' $f  | myuniq | gawk -v k=$k '{print(k,$1)}' >> px0log.dat
	else
	    echo $k NaN >> px0log.dat
	fi
	rm $f 2> /dev/null
	tail -1 px0log.dat
    done
fi
if [ $plot -eq 1 ];then
    proj=-JX-7/4
    fs=""
    for i in 1 2 3;do
	ofile=px0k.$i.ps
	if [ $i = 1 ];then
	    reg=-R0.852/1./-2.5/0.5
	    ann=-Ba0.02f0.002:"@~k@~'":/a0.5f0.1:y:
	elif [ $i = 2 ];then
	    reg=-R0.85/.868/-2.5/0.5
	    ann=-Ba0.002f0.0005:"@~k@~'":/a0.5f0.1:y:
	else
	    reg=-R0.832/0.855/-2/-1.3
	    ann=-Ba0.005f0.0005:"@~k@~'":/a0.2f.02:y:
	fi
	psbasemap $reg $proj -K -P $ann > $ofile
	psxy -Sc.01 -Gblue $reg $proj px0log.dat -O >> $ofile
	modifybb $ofile 0
	fs="$fs $ofile"
    done
    epsmerge -y 3 -par $fs > px0k.ps
    modifybb px0k.ps 1
    rm $fs

fi


