#!/bin/bash
run=${1-0}			# 1: add 2: replace
plot=${2-0}
kstart=${3-.85}
kstop=${4-1.}
kinc=${5-0.001}

tmpn=`mktemp`
trap "rm -f $tmpn*" EXIT

if [ $NR_CPUS -gt 64 ];then
    ncore=64
else
    ncore=$NR_CPUS
fi

lfile=px0log.dat
if [ $run -ne 0 ];then
    ks=`gawk -v k1=$kstart -v k2=$kstop -v ki=$kinc 'BEGIN{for(k=k1;k <= k2;k += ki)print(k)}'`
    if [ $run -eq 2 ];then
	rm $lfile 2> /dev/null
	echo $0: replacing with $ks
    else
	echo $0: adding $ks
    fi
    j=0
    for k in $ks;do
	(find_intersect $k  > tmp.k.$$.$k.dat )&
	if [ $j -ge $ncore ];then
	    wait
	    j=0
	fi
	((j=j+1))
    done
    wait
    cat tmp.k.$$.*.dat >> $lfile
    rm tmp.k.$$.*.dat 
    sort -g $lfile | uniq > tmp.dat ; mv tmp.dat $lfile
fi
if [ $plot -eq 1 ];then
    proj=-JX-7/4
    fs=""
    for i in 1 2 3;do
	ofile=px0k.$i.ps
	if [ $i = 1 ];then
	    reg=-R0.85/1./-2.5/0.5
	    ann=-Ba0.02f0.002:"@~k@~'":/a0.5f0.1:y:
	    gs=0.0025
	elif [ $i = 2 ];then
	    reg=-R0.8515/.867/-2.5/0.5
	    ann=-Ba0.002f0.0005:"@~k@~'":/a0.5f0.1:y:
	    gs=0.005
	else
	    reg=-R0.8515/0.8555/-2.2/-0.8
	    ann=-Ba0.001f0.0001:"@~k@~'":/a0.2f.05:y:
	    gs=0.01
	fi
	psbasemap $reg $proj -K -P $ann > $ofile
	psxy -Sc$gs -Gblue $reg $proj $lfile -O >> $ofile
	modifybb $ofile 0
	fs="$fs $ofile"
    done
    epsmerge -y 3 -par $fs > px0k.ps
    modifybb px0k.ps 1
    rm $fs

fi


