#!/usr/bin/env python3
# Translate the machine-generated MATLAB coefficient functions
# (Num1_2visc, Num2_2visc, Denom_2visc, antiplane_2visc_terms) from
# Plate_over_Maxwell_Layer_over_Halfspace_Displacements.m into C.
# The expressions are pure scalar arithmetic; only ^, abs and the
# P0(i,j) unpacking need conversion.
import re
import sys

SRC = 'Plate_over_Maxwell_Layer_over_Halfspace_Displacements.m'
OUT = 'terms_2visc.c'


def extract_functions(path):
    src = open(path).read().replace('\r\n', '\n')
    lines = src.split('\n')
    idx = [i for i, l in enumerate(lines) if re.match(r'\s*function\b', l)]
    idx.append(len(lines))
    funcs = {}
    for a, b in zip(idx[:-1], idx[1:]):
        block = '\n'.join(lines[a:b])
        mm = re.search(r'function\s*(?:\[[^\]]*\]\s*=\s*|\w+\s*=\s*)?(\w+)', block)
        funcs[mm.group(1)] = block
    return funcs


def join_continuations(body):
    body = re.sub(r'\.\.\.[^\n]*\n', ' ', body)
    return body


def strip_comments(line):
    out = []
    for ln in line.split('\n'):
        p = ln.find('%')
        if p >= 0:
            ln = ln[:p]
        out.append(ln)
    return '\n'.join(out)


def convert_pow(expr):
    # convert X^n (n integer literal, possibly negative) to pow(X,n),
    # handling parenthesized bases; right-to-left so nested cases work
    while True:
        p = expr.rfind('^')
        if p < 0:
            return expr
        # exponent
        m = re.match(r'\s*(-?\d+)', expr[p + 1:])
        if not m:
            raise SystemExit('non-integer exponent near: ' + expr[p - 30:p + 10])
        exp = m.group(1)
        eend = p + 1 + m.end()
        # base
        q = p - 1
        while q >= 0 and expr[q].isspace():
            q -= 1
        if expr[q] == ')':
            depth = 0
            r = q
            while r >= 0:
                if expr[r] == ')':
                    depth += 1
                elif expr[r] == '(':
                    depth -= 1
                    if depth == 0:
                        break
                r -= 1
            base_start = r
        else:
            r = q
            while r >= 0 and (expr[r].isalnum() or expr[r] in '._'):
                r -= 1
            base_start = r + 1
        base = expr[base_start:q + 1]
        expr = expr[:base_start] + 'pow(' + base + ',' + exp + ')' + expr[eend:]


def matlab_expr_to_c(expr):
    expr = convert_pow(expr)
    expr = re.sub(r'\babs\(', 'fabs(', expr)
    return expr


def get_assignments(block):
    body = join_continuations(strip_comments(block))
    # drop the function line
    body = re.sub(r'^\s*function[^\n]*\n', '', body)
    stmts = []
    for st in body.split(';'):
        st = st.strip()
        if not st:
            continue
        m = re.match(r'^(\w+)\s*=\s*(.+)$', st, re.S)
        if not m:
            continue
        stmts.append((m.group(1), ' '.join(m.group(2).split())))
    return stmts


def emit_function(fh, funcs, name, csig, unpack, outputs, skip_lhs=()):
    stmts = get_assignments(funcs[name])
    fh.write(csig + '\n{\n')
    fh.write(unpack)
    seen = set()
    for lhs, rhs in stmts:
        if lhs in skip_lhs:
            continue
        crhs = matlab_expr_to_c(rhs)
        if lhs in outputs:
            fh.write('  %s = %s;\n' % (outputs[lhs], crhs))
        else:
            decl = '' if lhs in seen else 'double '
            seen.add(lhs)
            fh.write('  %s%s = %s;\n' % (decl, lhs, crhs))
    fh.write('}\n\n')


def main():
    funcs = extract_functions(SRC)
    fh = open(OUT, 'w')
    fh.write('/* terms_2visc.c\n'
             ' *\n'
             ' * Machine-translated from the machine-generated (Mathematica)\n'
             ' * polynomial coefficient functions in\n'
             ' * Plate_over_Maxwell_Layer_over_Halfspace_Displacements.m\n'
             ' * (Kaj M. Johnson, Indiana University).\n'
             ' * Generated by gen_terms.py; do not edit by hand.\n'
             ' */\n'
             '#include <math.h>\n'
             '#include "pom.h"\n\n')

    unpack4 = ('  double P011,P012,P013,P014,P021,P022,P023,P024;\n'
               '  double P031,P032,P033,P034,P041,P042,P043,P044;\n'
               '  double C1,S1,Pf1,Pf2;\n'
               '  P011=P0[0][0];P012=P0[0][1];P013=P0[0][2];P014=P0[0][3];\n'
               '  P021=P0[1][0];P022=P0[1][1];P023=P0[1][2];P024=P0[1][3];\n'
               '  P031=P0[2][0];P032=P0[2][1];P033=P0[2][2];P034=P0[2][3];\n'
               '  P041=P0[3][0];P042=P0[3][1];P043=P0[3][2];P044=P0[3][3];\n'
               '  C1=cosh(k*d1);S1=sinh(k*d1);\n'
               '  Pf1=pf1;Pf2=pf2;\n'
               '  (void)P011;(void)P012;(void)P013;(void)P014;(void)P021;(void)P022;(void)P023;(void)P024;(void)P031;(void)P032;(void)P033;(void)P034;(void)P041;(void)P042;(void)P043;(void)P044;(void)C1;(void)S1;(void)Pf1;(void)Pf2;(void)u;\n')
    unpack4_nof = ('  double P011,P012,P013,P014,P021,P022,P023,P024;\n'
                   '  double P031,P032,P033,P034,P041,P042,P043,P044;\n'
                   '  double C1,S1;\n'
                   '  P011=P0[0][0];P012=P0[0][1];P013=P0[0][2];P014=P0[0][3];\n'
                   '  P021=P0[1][0];P022=P0[1][1];P023=P0[1][2];P024=P0[1][3];\n'
                   '  P031=P0[2][0];P032=P0[2][1];P033=P0[2][2];P034=P0[2][3];\n'
                   '  P041=P0[3][0];P042=P0[3][1];P043=P0[3][2];P044=P0[3][3];\n'
                   '  C1=cosh(k*d1);S1=sinh(k*d1);\n'
                   '  (void)P011;(void)P012;(void)P013;(void)P014;(void)P021;(void)P022;(void)P023;(void)P024;(void)P031;(void)P032;(void)P033;(void)P034;(void)P041;(void)P042;(void)P043;(void)P044;(void)C1;(void)S1;(void)u;\n')
    unpack2 = ('  double Ph11,Ph12,Ph21,Ph22,C1,Z1,Pf1,Pf2;\n'
               '  Ph11=P0[0][0];Ph12=P0[0][1];Ph21=P0[1][0];Ph22=P0[1][1];\n'
               '  C1=cosh(fabs(k)*d1);Z1=sinh(fabs(k)*d1);\n'
               '  Pf1=pf1;Pf2=pf2;\n'
               '  (void)Ph11;(void)Ph12;(void)Pf1;(void)Pf2;\n'
               '  (void)B2;\n')

    outN = {('N%d' % i): ('N[%d]' % (i - 1)) for i in range(1, 9)}
    outD = {('D%d' % i): ('D[%d]' % (i - 1)) for i in range(1, 9)}

    emit_function(fh, funcs, 'Num1_2visc',
                  'void num1_2visc(double pf1, double pf2, double B1, double B2,\n'
                  '                double K, double k, double d1,\n'
                  '                double P0[4][4], double u, double *N)',
                  unpack4, outN, skip_lhs=('Pf1', 'Pf2', 'C1', 'S1',
                                           'P011', 'P012', 'P013', 'P014',
                                           'P021', 'P022', 'P023', 'P024',
                                           'P031', 'P032', 'P033', 'P034',
                                           'P041', 'P042', 'P043', 'P044'))
    emit_function(fh, funcs, 'Num2_2visc',
                  'void num2_2visc(double pf1, double pf2, double B1, double B2,\n'
                  '                double K, double k, double d1,\n'
                  '                double P0[4][4], double u, double *N)',
                  unpack4, outN, skip_lhs=('Pf1', 'Pf2', 'C1', 'S1',
                                           'P011', 'P012', 'P013', 'P014',
                                           'P021', 'P022', 'P023', 'P024',
                                           'P031', 'P032', 'P033', 'P034',
                                           'P041', 'P042', 'P043', 'P044'))
    emit_function(fh, funcs, 'Denom_2visc',
                  'void denom_2visc(double B1, double B2, double K, double k,\n'
                  '                 double d1, double P0[4][4], double u, double *D)',
                  unpack4_nof, outD, skip_lhs=('C1', 'S1',
                                               'P011', 'P012', 'P013', 'P014',
                                               'P021', 'P022', 'P023', 'P024',
                                               'P031', 'P032', 'P033', 'P034',
                                               'P041', 'P042', 'P043', 'P044'))
    outA = {'N1': 'N[0]', 'N2': 'N[1]', 'N3': 'N[2]',
            'D1': 'D[0]', 'D2': 'D[1]', 'D3': 'D[2]'}
    emit_function(fh, funcs, 'antiplane_2visc_terms',
                  'void antiplane_2visc_terms(double pf1, double pf2, double B1,\n'
                  '                           double B2, double k, double d1,\n'
                  '                           double P0[2][2], double u,\n'
                  '                           double *N, double *D)',
                  unpack2, outA, skip_lhs=('Pf1', 'Pf2', 'C1', 'Z1',
                                           'Ph11', 'Ph12', 'Ph21', 'Ph22'))
    fh.close()
    print('wrote', OUT)


if __name__ == '__main__':
    main()
