#!/bin/bash
mtest=${1-1}

if [ $mtest -eq 1 ];then	# scaling python
    nx=120
    nz=200
    dx=250
    
    # thread scaling: same physics, fixed wall time, compare steps reached
    for threads in 1 4 8; do
	python3 bp1_pt.py --numba --threads $threads --nx $nx --nz $nz --Lx 30e3 --Lz 50e3 \
		--t_end_yr 320 --tol_pa 1.0 --out_every 100 --wall_limit 300 \
		--log scale$dx.$threads.csv
	echo scaling $threads `tail -n 1 scale$dx.$threads.csv | cut -d, -f1,2`
    done
    ./test_scaling
elif [ $mtest -eq 2 ];then	# run python
 
    for dx in 125 250;do
	if [ $dx = 250 ];then
	    nx=120;nz=200
	    nthreads="4"
	elif [ $dx = 125 ];then
	    nx=240;nz=400
	    nthreads="4"
	fi
	echo run $nx $nz $dx
	for threads in $nthreads;do
	    python3 bp1_pt.py --numba --threads $threads --nx $nx --nz $nz --Lx 30e3 --Lz 50e3 \
		    --t_end_yr 320 --tol_pa 1.0 --out_every 500 \
		    --log "run"$dx.$threads".csv" --checkpoint "ck"$dx.$threads".npz"
	done
    done
elif [ $mtest -eq 3 ];then	# compare python vs. Julia

    python3 bp1_pt.py --threads 4 --numba --nx 120 --nz 200 --Lx 30e3 --Lz 50e3 --t_end_yr 6 --out_every 1 --log py6.csv
    
    julia -t 4 -e 'include("bp1_pt.jl"); run_bp1(nx=120, nz=200, Lx=30e3, Lz=50e3, t_end_yr=6.0, out_every=1, check_every=1, logfile="jl6.csv")'
    ./test_julia
fi
    
