#!/bin/bash
#
# step 1 + 2 checks for the visco-elastic Prony machinery
# (rsf_ve_implementation_plan.md); run from test_ve/
#
# hardcoded parameters; resolve the binary directory to an absolute
# path so it survives the cd into the scratch directory
bindir=`cd ../bin && pwd`
tau_m=1.0
tol=1e-9
tmpd=tmp_ve_tests
#
mkdir -p $tmpd
cd $tmpd
fail=0
# 2D segments, buried below y = 0 so the surface profile is physical
$bindir/makefault -n 200 2> /dev/null | \
    gawk '{printf("%22.15e %22.15e",$1,$2-1.0005);for(i=3;i<=NF;i++)printf(" %s",$i);printf("\n")}' > geom.in
$bindir/ve_check $tau_m $tol || fail=1
$bindir/relax_fault_ve 0.1 0 0.4 0.6 $tau_m 0   10 2> /dev/null || fail=1
$bindir/relax_fault_ve 0.1 0 0.4 0.6 $tau_m 0.5 10 2> /dev/null || fail=1
# 3D Okada rectangles
$bindir/makefault -n 16 -m 8 -l 2 -w 1 -z -3 -dip 70 > geom.in 2> /dev/null
$bindir/ve_check $tau_m $tol || fail=1
$bindir/relax_fault_ve 0.1 1 0.3 0.7 $tau_m 0.5 10 2> /dev/null || fail=1
# triangles
printf "0.33 0.33 -1.33 0 0 -1 -1 0 0 0 -2 1 0 -2 0 1 -1\n0.67 0.67 -1.67 0 0 -1 -1 0 1 0 -2 1 1 -1 0 1 -1\n" > geom.in
$bindir/ve_check $tau_m $tol || fail=1
cd ..
if [ $fail -eq 0 ];then
    echo $0: all VE checks passed
else
    echo $0: FAILURES, see above
fi
